CREATE TABLE `virtual_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`display_name` text NOT NULL,
	`account_type` text NOT NULL,
	`profession` text NOT NULL,
	`specialty` text,
	`location` text,
	`bio` text,
	`avatar` text,
	`is_virtual` integer DEFAULT 1 NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE INDEX `idx_virtual_profiles_type` ON `virtual_profiles` (`account_type`);
--> statement-breakpoint
CREATE INDEX `idx_virtual_profiles_profession` ON `virtual_profiles` (`profession`);
--> statement-breakpoint
INSERT INTO `virtual_profiles` (`id`,`display_name`,`account_type`,`profession`,`specialty`,`location`,`bio`,`avatar`,`is_virtual`) VALUES
('virtual-member-001','Nguyễn Minh Anh','member','Thành viên',NULL,'TP. Hồ Chí Minh','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-002','Trần Quốc Bảo','member','Thành viên',NULL,'Hà Nội','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-003','Lê Hoàng Nam','member','Thành viên',NULL,'Đà Nẵng','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-004','Phạm Thu Hà','member','Thành viên',NULL,'Bình Dương','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-005','Võ Gia Huy','member','Thành viên',NULL,'Đồng Nai','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-006','Đặng Ngọc Lan','member','Thành viên',NULL,'Cần Thơ','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-007','Bùi Thanh Tùng','member','Thành viên',NULL,'Hải Phòng','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-008','Đỗ Khánh Linh','member','Thành viên',NULL,'Khánh Hòa','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-009','Nguyễn Đức Anh','member','Thành viên',NULL,'TP. Hồ Chí Minh','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-010','Trần Mai Phương','member','Thành viên',NULL,'Hà Nội','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-011','Lê Quang Huy','member','Thành viên',NULL,'Đà Nẵng','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-012','Phạm Minh Châu','member','Thành viên',NULL,'Bình Dương','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-013','Võ Tuấn Kiệt','member','Thành viên',NULL,'Đồng Nai','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-014','Đặng Thùy Dương','member','Thành viên',NULL,'Cần Thơ','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-015','Bùi Quốc Việt','member','Thành viên',NULL,'Hải Phòng','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-016','Đỗ Bảo Ngọc','member','Thành viên',NULL,'Khánh Hòa','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-017','Nguyễn Hải Đăng','member','Thành viên',NULL,'TP. Hồ Chí Minh','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-018','Trần Kim Oanh','member','Thành viên',NULL,'Hà Nội','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-019','Lê Thành Công','member','Thành viên',NULL,'Đà Nẵng','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-member-020','Phạm Ngọc Ánh','member','Thành viên',NULL,'Bình Dương','Đang chuẩn bị hoặc đã có kinh nghiệm xây nhà.','/avatars/user-nguyen-van-a.png',1),
('virtual-architect-001','KTS. Nguyễn Khánh Linh','expert','Kiến trúc sư','Thiết kế nhà phố','TP. Hồ Chí Minh','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-khanh-linh.png',1),
('virtual-architect-002','KTS. Trần Minh Khoa','expert','Kiến trúc sư','Thiết kế biệt thự','Hà Nội','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-vu-mai.png',1),
('virtual-architect-003','KTS. Lê Hoài An','expert','Kiến trúc sư','Kiến trúc xanh','Đà Nẵng','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-architect-004','KTS. Phạm Đức Long','expert','Kiến trúc sư','Thiết kế nội thất','Bình Dương','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-khanh-linh.png',1),
('virtual-architect-005','KTS. Võ Thanh Trúc','expert','Kiến trúc sư','Quy hoạch không gian','Đồng Nai','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-vu-mai.png',1),
('virtual-architect-006','KTS. Đặng Quang Vinh','expert','Kiến trúc sư','Thiết kế nhà phố','Cần Thơ','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-architect-007','KTS. Bùi Ngọc Mai','expert','Kiến trúc sư','Thiết kế biệt thự','Hải Phòng','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-khanh-linh.png',1),
('virtual-architect-008','KTS. Đỗ Anh Tuấn','expert','Kiến trúc sư','Kiến trúc xanh','Khánh Hòa','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-vu-mai.png',1),
('virtual-architect-009','KTS. Nguyễn Thảo Vy','expert','Kiến trúc sư','Thiết kế nội thất','TP. Hồ Chí Minh','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-architect-010','KTS. Trần Quốc Khánh','expert','Kiến trúc sư','Quy hoạch không gian','Hà Nội','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-khanh-linh.png',1),
('virtual-architect-011','KTS. Lê Minh Thư','expert','Kiến trúc sư','Thiết kế nhà phố','Đà Nẵng','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-vu-mai.png',1),
('virtual-architect-012','KTS. Phạm Gia Bảo','expert','Kiến trúc sư','Thiết kế biệt thự','Bình Dương','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-architect-013','KTS. Võ Hải Yến','expert','Kiến trúc sư','Kiến trúc xanh','Đồng Nai','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-khanh-linh.png',1),
('virtual-architect-014','KTS. Đặng Thành Nam','expert','Kiến trúc sư','Thiết kế nội thất','Cần Thơ','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/expert-vu-mai.png',1),
('virtual-architect-015','KTS. Bùi Phương Anh','expert','Kiến trúc sư','Quy hoạch không gian','Hải Phòng','Kiến trúc sư tư vấn cộng đồng Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-001','KS. Nguyễn Trọng Hiếu','expert','Kỹ sư xây dựng','Kết cấu công trình','TP. Hồ Chí Minh','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-002','KS. Trần Văn Hùng','expert','Kỹ sư xây dựng','Giám sát thi công','Hà Nội','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-003','KS. Lê Quốc Đạt','expert','Kỹ sư xây dựng','Dự toán xây dựng','Đà Nẵng','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-004','KS. Phạm Minh Tâm','expert','Kỹ sư xây dựng','MEP công trình','Bình Dương','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-005','KS. Võ Đức Thịnh','expert','Kỹ sư xây dựng','Quản lý dự án','Đồng Nai','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-006','KS. Đặng Hoàng Sơn','expert','Kỹ sư xây dựng','Kết cấu công trình','Cần Thơ','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-007','KS. Bùi Tuấn Anh','expert','Kỹ sư xây dựng','Giám sát thi công','Hải Phòng','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-008','KS. Đỗ Thanh Bình','expert','Kỹ sư xây dựng','Dự toán xây dựng','Khánh Hòa','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-009','KS. Nguyễn Quang Hào','expert','Kỹ sư xây dựng','MEP công trình','TP. Hồ Chí Minh','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-010','KS. Trần Ngọc Phúc','expert','Kỹ sư xây dựng','Quản lý dự án','Hà Nội','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-011','KS. Lê Thành Đạt','expert','Kỹ sư xây dựng','Kết cấu công trình','Đà Nẵng','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-012','KS. Phạm Quốc Trung','expert','Kỹ sư xây dựng','Giám sát thi công','Bình Dương','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-013','KS. Võ Minh Nhật','expert','Kỹ sư xây dựng','Dự toán xây dựng','Đồng Nai','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1),
('virtual-engineer-014','KS. Đặng Anh Dũng','expert','Kỹ sư xây dựng','MEP công trình','Cần Thơ','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/user-nguyen-van-a.png',1),
('virtual-engineer-015','KS. Bùi Hải Nam','expert','Kỹ sư xây dựng','Quản lý dự án','Hải Phòng','Kỹ sư chia sẻ kinh nghiệm kỹ thuật trên Tipook.','/avatars/expert-trong-hieu.png',1);
