"use client";
import { EditableText } from "@/components/site-editor";
import {useMemo,useState} from "react";
import {Calculator,ChevronRight} from "lucide-react";

type ItemId="blinding"|"footing"|"pedestal"|"gradeBeam"|"column"|"beam"|"slab"|"stair"|"floorBase"|"masonry"|"plaster"|"floorTile"|"wallTile"|"paint";
type Result={label:string;value:string;note?:string};
type FootingType="isolated"|"combined"|"stepped"|"strip"|"raft"|"pile";
const footingTypes:readonly (readonly [FootingType,string])[]=[
 ["isolated","Móng đơn vát"],["combined","Móng liên hợp bản phẳng (2 cột)"],["stepped","Móng đơn giật cấp"],["strip","Móng băng tiết diện vát"],["raft","Móng bè bản phẳng"],["pile","Đài cọc + cọc tròn BTCT"]
];
const groups:readonly {title:string;items:readonly (readonly [ItemId,string])[]}[]=[
 {title:"Kết cấu bê tông",items:[["blinding","Bê tông lót"],["footing","Bê tông móng"],["pedestal","Bê tông cổ cột"],["gradeBeam","Bê tông đà kiềng"],["column","Bê tông cột"],["beam","Bê tông dầm"],["slab","Bê tông sàn"],["stair","Bê tông cầu thang"]]},
 {title:"Xây và lớp nền",items:[["floorBase","Ba ta nền"],["masonry","Gạch xây tường"],["plaster","Trát tường"]]},
 {title:"Hoàn thiện",items:[["floorTile","Gạch lát nền"],["wallTile","Gạch ốp tường"],["paint","Sơn nước"]]},
] as const;
const names=Object.fromEntries(groups.flatMap(g=>g.items)) as Record<ItemId,string>;
const defaults:Record<string,string>={qty:"1",waste:"3",length:"5",width:".2",height:".3",thickness:".1",openings:"0",bottomA:"2",bottomB:"2",topA:"1",topB:"1",totalH:".8",baseH:".25",rise:".17",tread:".25",steps:"18",stairWidth:"1",waist:".12",upperH:".4",pileDiameter:".3",pileLength:"6",pileCount:"4",sides:"2",tileW:".6",tileH:".6",coverage:"10",coats:"2"};
const mixes={M100:{cement:218,sand:.516,stone:.831,water:185},M150:{cement:250,sand:.505,stone:.824,water:190},M200:{cement:277,sand:.503,stone:.82,water:198},M250:{cement:323,sand:.492,stone:.803,water:198},M300:{cement:366,sand:.482,stone:.787,water:198}};
const fmt=(v:number,d=3)=>new Intl.NumberFormat("vi-VN",{maximumFractionDigits:d}).format(v);
const n=(v:string)=>{const x=Number((v||"").replace(",","."));return Number.isFinite(x)&&x>0?x:0};
const concreteIds=new Set<ItemId>(["blinding","footing","pedestal","gradeBeam","column","beam","slab","stair"]);

function Field({label,k,v,set,unit="m",step="0.01"}:{label:string;k:string;v:Record<string,string>;set:(k:string,x:string)=>void;unit?:string;step?:string}){
 return <label><span className="mb-1 block text-xs font-bold text-[#344054]">{label}</span><span className="flex h-9 overflow-hidden rounded-xl border border-[#dce5ef] bg-white focus-within:border-[#229ed9] focus-within:ring-4 focus-within:ring-[#229ed9]/10"><input type="number" aria-label={label} data-measurement={k} min="0" step={step} value={v[k]} onChange={e=>set(k,e.target.value)} className="min-w-0 flex-1 px-3 text-sm font-semibold outline-none"/><span className="grid min-w-12 place-items-center border-l bg-[#f7f9fb] px-2 text-xs font-bold text-[#667085]">{unit}</span></span></label>
}
function FootingPreview({type}:{type:FootingType}){
 type P3=readonly [number,number,number];
 const project=([x,y,z]:P3):[number,number]=>[260+(x-y)*48,225+(x+y)*22-z*76];
 const points=(items:P3[])=>items.map(point=>project(point).join(",")).join(" ");
 const corners=(width:number,depth:number,z:number):P3[]=>[[-width/2,-depth/2,z],[width/2,-depth/2,z],[width/2,depth/2,z],[-width/2,depth/2,z]];
 const solid=(bottomWidth:number,bottomDepth:number,topWidth:number,topDepth:number,z0:number,z1:number)=>{const lower=corners(bottomWidth,bottomDepth,z0),upper=corners(topWidth,topDepth,z1);return <g stroke="#0b4f88" strokeWidth="1.8" strokeLinejoin="round"><polygon points={points([lower[0],lower[1],upper[1],upper[0]])} fill="#d8eff9"/><polygon points={points([lower[1],lower[2],upper[2],upper[1]])} fill="#acdcef"/><polygon points={points([lower[2],lower[3],upper[3],upper[2]])} fill="#91cde5"/><polygon points={points([lower[3],lower[0],upper[0],upper[3]])} fill="#c6e8f5"/><polygon points={points(upper)} fill="#eaf8fd"/></g>};
 const dim=(a:P3,b:P3,label:string,dx=0,dy=0)=>{const p1=project(a),p2=project(b),mx=(p1[0]+p2[0])/2+dx,my=(p1[1]+p2[1])/2+dy;return <g><line x1={p1[0]} y1={p1[1]} x2={p2[0]} y2={p2[1]} stroke="#168ac0" strokeWidth="1.4" markerStart="url(#dim-arrow)" markerEnd="url(#dim-arrow)"/><rect x={mx-13} y={my-10} width="26" height="18" rx="6" fill="white" opacity=".94"/><text x={mx} y={my+3} textAnchor="middle" fill="#0879ad" fontSize="12" fontWeight="800">{label}</text></g>};
 const captions:Record<FootingType,string>={
  isolated:"A, B: kích thước đáy · a, b: kích thước mặt trên · H: tổng chiều cao · h: chiều dày bản đế móng BTCT (không phải lớp lót)",
  combined:"L, B: kích thước bản móng liên hợp · H: chiều dày bản · hai ô nét đứt: vị trí cột/cổ cột, không cộng thể tích",
  stepped:"A, B: bậc dưới · a, b: bậc trên · h₁, h₂: chiều cao từng bậc",
  strip:"L: tổng chiều dài · B: rộng đáy · b: rộng mặt trên · H: tổng cao · h: dày bản đế móng băng BTCT (không phải lớp lót)",
  raft:"L, W: kích thước mặt bằng · t: chiều dày bản móng bè",
  pile:"A, B, H: kích thước đài · d: đường kính cọc · Lc: chiều dài cọc"
 };
 let geometry:React.ReactNode;
 if(type==="raft")geometry=<>{solid(4.4,2.7,4.4,2.7,0,.34)}{dim([-2.2,1.62,0],[2.2,1.62,0],"L",0,18)}{dim([2.55,-1.35,0],[2.55,1.35,0],"W",18,0)}{dim([-2.45,-1.35,0],[-2.45,-1.35,.34],"t",-18,0)}</>;
 else if(type==="pile"){
  const pilePoints:P3[]=[[-1.35,-.72,0],[1.35,-.72,0],[-1.35,.72,0],[1.35,.72,0]];
  geometry=<><g>{pilePoints.map((point,index)=>{const top: P3=[point[0],point[1],1.68],p0=project(point),p1=project(top);return <g key={index}><line x1={p0[0]} y1={p0[1]} x2={p1[0]} y2={p1[1]} stroke="#397796" strokeWidth="11" strokeLinecap="round"/><ellipse cx={p0[0]} cy={p0[1]} rx="6" ry="3" fill="#0b4f88"/></g>})}</g>{solid(3.4,2.15,3.4,2.15,1.45,2.12)}{dim([-1.7,1.36,1.45],[1.7,1.36,1.45],"A",0,17)}{dim([2.02,-1.075,1.45],[2.02,1.075,1.45],"B",18,0)}{dim([-2,-1.075,1.45],[-2,-1.075,2.12],"H",-18,0)}{dim([1.75,-1.075,0],[1.75,-1.075,1.45],"Lc",20,0)}{dim([-1.51,-.72,0],[-1.19,-.72,0],"d",0,17)}</>;
 }
 else if(type==="stepped")geometry=<>{solid(3.9,2.55,3.9,2.55,0,.38)}{solid(2.25,1.38,2.25,1.38,.38,1.05)}{dim([-1.95,1.55,0],[1.95,1.55,0],"A",0,18)}{dim([2.3,-1.275,0],[2.3,1.275,0],"B",18,0)}{dim([-1.125,-1.08,1.05],[1.125,-1.08,1.05],"a",0,-16)}{dim([1.5,-.69,1.05],[1.5,.69,1.05],"b",18,0)}{dim([-2.2,-1.275,0],[-2.2,-1.275,.38],"h₁",-19,0)}{dim([-1.45,-.69,.38],[-1.45,-.69,1.05],"h₂",-19,0)}</>;
 else if(type==="combined"){
  const left=corners(.62,.62,.5).map(([x,y,z])=>[x-1.15,y,z] as P3),right=corners(.62,.62,.5).map(([x,y,z])=>[x+1.15,y,z] as P3);
  geometry=<>{solid(4.5,2.4,4.5,2.4,0,.5)}<polygon points={points(left)} fill="none" stroke="#d92d20" strokeWidth="2" strokeDasharray="6 4"/><polygon points={points(right)} fill="none" stroke="#d92d20" strokeWidth="2" strokeDasharray="6 4"/>{dim([-2.25,1.58,0],[2.25,1.58,0],"L",0,18)}{dim([2.62,-1.2,0],[2.62,1.2,0],"B",18,0)}{dim([-2.55,-1.2,0],[-2.55,-1.2,.5],"H",-18,0)}<text x="260" y="73" textAnchor="middle" fill="#d92d20" fontSize="10" fontWeight="700">VỊ TRÍ 2 CỘT / CỔ CỘT</text></>;
 }
 else if(type==="strip")geometry=<>{solid(4.7,1.75,4.7,1.75,0,.3)}{solid(4.7,1.75,4.7,.72,.3,1.05)}{dim([-2.35,1.22,0],[2.35,1.22,0],"L",0,18)}{dim([2.72,-.875,0],[2.72,.875,0],"B",18,0)}{dim([2.72,-.36,1.05],[2.72,.36,1.05],"b",18,0)}{dim([-2.65,-.875,0],[-2.65,-.875,1.05],"H",-18,0)}{dim([-2.65,.875,0],[-2.65,.875,.3],"h",-18,0)}</>;
 else {
  const width=3.6,topWidth=1.75;
  geometry=<>{solid(width,2.55,width,2.55,0,.3)}{solid(width,2.55,topWidth,1.15,.3,1.2)}{dim([-width/2,1.62,0],[width/2,1.62,0],"A",0,18)}{dim([width/2+.38,-1.275,0],[width/2+.38,1.275,0],"B",18,0)}{dim([-topWidth/2,-.9,1.2],[topWidth/2,-.9,1.2],"a",0,-16)}{dim([topWidth/2+.35,-.575,1.2],[topWidth/2+.35,.575,1.2],"b",18,0)}{dim([-width/2-.35,-1.275,0],[-width/2-.35,-1.275,1.2],"H",-18,0)}{dim([-width/2-.35,1.275,0],[-width/2-.35,1.275,.3],"h",-18,0)}</>;
 }
 return <figure className="mt-3 overflow-hidden rounded-xl border border-[#dce5ef] bg-white"><div className="flex items-center justify-between border-b bg-[#f8fafc] px-3 py-2"><b className="text-xs text-[#344054]">Hình mô phỏng không gian</b><span className="text-[11px] text-[#667085]">Hình quy ước · Không theo tỷ lệ</span></div><svg viewBox="0 0 520 300" role="img" aria-label={`Hình mô phỏng ${footingTypes.find(([id])=>id===type)?.[1]}`} className="mx-auto block h-auto w-full max-w-[540px] p-2"><defs><marker id="dim-arrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto-start-reverse"><path d="M0,0 L7,3.5 L0,7 Z" fill="#168ac0"/></marker></defs>{geometry}</svg><figcaption className="border-t px-3 py-2 text-[11px] leading-5 text-[#52677f]">{captions[type]}</figcaption></figure>;
}
function StandardFields({item,footingType,v,set}:{item:ItemId;footingType:FootingType;v:Record<string,string>;set:(k:string,x:string)=>void}){
 const F=(p:{label:string;k:string;unit?:string;step?:string})=><Field {...p} v={v} set={set}/>;
 if(item==="footing"){
  if(footingType==="strip")return <>{F({label:"Tổng chiều dài móng băng",k:"length"})}{F({label:"B — rộng đáy móng",k:"bottomB"})}{F({label:"b — rộng mặt trên",k:"topB"})}{F({label:"H — tổng chiều cao",k:"totalH"})}{F({label:"h — dày bản đế móng BTCT",k:"baseH"})}</>;
  if(footingType==="raft")return <>{F({label:"Chiều dài móng bè",k:"length"})}{F({label:"Chiều rộng móng bè",k:"width"})}{F({label:"Chiều dày bản móng",k:"thickness"})}</>;
  if(footingType==="combined")return <>{F({label:"L — chiều dài bản móng liên hợp",k:"length"})}{F({label:"B — chiều rộng bản móng",k:"width"})}{F({label:"H — chiều dày bản móng",k:"height"})}</>;
  if(footingType==="pile")return <>{F({label:"Chiều dài đài cọc",k:"length"})}{F({label:"Chiều rộng đài cọc",k:"width"})}{F({label:"Chiều cao đài cọc",k:"height"})}{F({label:"Đường kính cọc",k:"pileDiameter"})}{F({label:"Chiều dài mỗi cọc",k:"pileLength"})}{F({label:"Số cọc trong một đài",k:"pileCount",unit:"cọc",step:"1"})}</>;
  if(footingType==="stepped")return <>{F({label:"A — dài bậc dưới",k:"bottomA"})}{F({label:"B — rộng bậc dưới",k:"bottomB"})}{F({label:"Chiều cao bậc dưới",k:"baseH"})}{F({label:"a — dài bậc trên",k:"topA"})}{F({label:"b — rộng bậc trên",k:"topB"})}{F({label:"Chiều cao bậc trên",k:"upperH"})}</>;
  return <>{F({label:"A — chiều dài đáy",k:"bottomA"})}{F({label:"B — chiều rộng đáy",k:"bottomB"})}{F({label:"a — chiều dài mặt trên",k:"topA"})}{F({label:"b — chiều rộng mặt trên",k:"topB"})}{F({label:"H — tổng chiều cao",k:"totalH"})}{F({label:"h — dày bản đế móng BTCT",k:"baseH"})}</>;
 }
 if(item==="stair")return <>{F({label:"Chiều rộng vế thang",k:"stairWidth"})}{F({label:"Chiều cao bậc",k:"rise"})}{F({label:"Chiều rộng mặt bậc",k:"tread"})}{F({label:"Số bậc",k:"steps",unit:"bậc",step:"1"})}{F({label:"Chiều dày bản thang",k:"waist"})}</>;
 if(["blinding","slab","floorBase","floorTile"].includes(item))return <>{F({label:"Chiều dài",k:"length"})}{F({label:"Chiều rộng",k:"width"})}{item!=="floorTile"&&F({label:"Chiều dày",k:"thickness"})}{item==="floorTile"&&<>{F({label:"Cạnh dài viên gạch",k:"tileW"})}{F({label:"Cạnh rộng viên gạch",k:"tileH"})}</>}</>;
 if(["masonry","plaster","wallTile","paint"].includes(item))return <>{F({label:"Tổng chiều dài tường",k:"length"})}{F({label:"Chiều cao tường",k:"height"})}{F({label:"Diện tích cửa cần trừ",k:"openings",unit:"m²"})}{item==="masonry"&&F({label:"Chiều dày tường",k:"thickness"})}{item==="plaster"&&<>{F({label:"Chiều dày lớp trát",k:"thickness"})}{F({label:"Số mặt trát",k:"sides",unit:"mặt",step:"1"})}</>}{item==="wallTile"&&<>{F({label:"Cạnh dài viên gạch",k:"tileW"})}{F({label:"Cạnh rộng viên gạch",k:"tileH"})}</>}{item==="paint"&&<>{F({label:"Số mặt sơn",k:"sides",unit:"mặt",step:"1"})}{F({label:"Độ phủ sơn",k:"coverage",unit:"m²/L"})}{F({label:"Số lớp phủ",k:"coats",unit:"lớp",step:"1"})}</>}</>;
 if(["pedestal","column"].includes(item))return <>{F({label:"Chiều cao cấu kiện",k:"length"})}{F({label:"Cạnh thứ nhất",k:"width"})}{F({label:"Cạnh thứ hai",k:"height"})}</>;
 if(["gradeBeam","beam"].includes(item))return <>{F({label:"Tổng chiều dài",k:"length"})}{F({label:"Bề rộng",k:"width"})}{F({label:"Chiều cao",k:"height"})}</>;
 return <>{F({label:"Chiều dài",k:"length"})}{F({label:"Chiều rộng",k:"width"})}{F({label:"Chiều cao",k:"height"})}</>;
}

export function MaterialCalculator(){
 const [item,setItem]=useState<ItemId>("blinding"),[footingType,setFootingType]=useState<FootingType>("isolated"),[v,setV]=useState(defaults),[grade,setGrade]=useState<keyof typeof mixes>("M100");
 const set=(k:string,x:string)=>setV(s=>({...s,[k]:x}));
 const chooseItem=(id:ItemId)=>{setItem(id);setGrade(current=>id==="blinding"?(current==="M100"||current==="M150"?current:"M100"):(current==="M100"||current==="M150"?"M250":current))};
 const results=useMemo(()=>{const q=n(v.qty),loss=1+n(v.waste)/100;let primary=0;const out:Result[]=[];
  if(item==="footing"){
   if(footingType==="combined"){const combined=n(v.length)*n(v.width)*n(v.height);primary=combined*q;out.push({label:"Bản móng liên hợp BTCT",value:fmt(primary)+" m³",note:"Không gồm cổ cột"})}
   else if(footingType==="raft"){const raft=n(v.length)*n(v.width)*n(v.thickness);primary=raft*q;out.push({label:"Bản móng bè",value:fmt(primary)+" m³"})}
   else if(footingType==="pile"){const cap=n(v.length)*n(v.width)*n(v.height),piles=Math.PI*Math.pow(n(v.pileDiameter),2)/4*n(v.pileLength)*n(v.pileCount);primary=(cap+piles)*q;out.push({label:"Bê tông đài cọc",value:fmt(cap*q)+" m³"},{label:"Bê tông cọc BTCT",value:fmt(piles*q)+" m³",note:fmt(n(v.pileCount)*q,0)+" cọc"})}
   else if(footingType==="strip"){const L=n(v.length),B=n(v.bottomB),b=n(v.topB),H=n(v.totalH),h=Math.min(n(v.baseH),H),s=Math.max(H-h,0),base=L*B*h,bevel=L*(B+b)/2*s;primary=(base+bevel)*q;out.push({label:"Bản đế móng băng BTCT",value:fmt(base*q)+" m³"},{label:"Phần vát móng băng",value:fmt(bevel*q)+" m³"})}
   else if(footingType==="stepped"){const lower=n(v.bottomA)*n(v.bottomB)*n(v.baseH),upper=n(v.topA)*n(v.topB)*n(v.upperH);primary=(lower+upper)*q;out.push({label:"Bậc móng dưới",value:fmt(lower*q)+" m³"},{label:"Bậc móng trên",value:fmt(upper*q)+" m³"})}
   else {const A=n(v.bottomA),B=n(v.bottomB),a=n(v.topA),b=n(v.topB),H=n(v.totalH),h=Math.min(n(v.baseH),H),s=Math.max(H-h,0),base=A*B*h,bevel=s/6*(2*A*B+2*a*b+A*b+a*B);primary=(base+bevel)*q;out.push({label:"Bản đế móng BTCT",value:fmt(base*q)+" m³"},{label:"Phần vát móng BTCT",value:fmt(bevel*q)+" m³"})}
  }
  else if(item==="stair"){const rise=n(v.rise),tread=n(v.tread),steps=n(v.steps),W=n(v.stairWidth),waist=n(v.waist);const inclined=Math.hypot(rise*steps,tread*steps);const slab=inclined*W*waist,stepsVol=steps*rise*tread*W/2;primary=(slab+stepsVol)*q;out.push({label:"Bản thang nghiêng",value:fmt(slab*q)+" m³"},{label:"Các bậc",value:fmt(stepsVol*q)+" m³"})}
  else if(["pedestal","gradeBeam","column","beam"].includes(item))primary=n(v.length)*n(v.width)*n(v.height)*q;
  else if(["blinding","slab","floorBase"].includes(item))primary=n(v.length)*n(v.width)*n(v.thickness)*q;
  else {const gross=n(v.length)*n(v.height)*q,net=Math.max(gross-n(v.openings),0);
   if(item==="masonry"){const vol=net*n(v.thickness);const mortar=vol*.28*loss;out.push({label:"Diện tích tường",value:fmt(net)+" m²"},{label:"Khối lượng tường",value:fmt(vol)+" m³"},{label:"Gạch tiêu chuẩn",value:Math.ceil(vol*550*loss)+" viên",note:"Gạch 220×105×60 mm"},{label:"Vữa xây",value:fmt(mortar)+" m³"},{label:"Xi măng xây",value:fmt(mortar*300,0)+" kg"},{label:"Cát xây",value:fmt(mortar*1.05)+" m³"});return {primary:vol,out}}
   if(item==="plaster"){const area=net*n(v.sides),mortar=area*n(v.thickness)*loss;out.push({label:"Diện tích trát",value:fmt(area)+" m²"},{label:"Vữa trát",value:fmt(mortar)+" m³"},{label:"Xi măng",value:fmt(mortar*300,0)+" kg"},{label:"Cát mịn",value:fmt(mortar*1.05)+" m³"});return {primary:area,out}}
   if(item==="wallTile"){const area=net*loss,tile=n(v.tileW)*n(v.tileH);out.push({label:"Diện tích mua",value:fmt(area)+" m²"},{label:"Số viên gạch",value:Math.ceil(area/tile)+" viên"},{label:"Keo dán gạch",value:fmt(area*5,0)+" kg"});return {primary:area,out}}
   if(item==="paint"){const area=net*n(v.sides),liters=area*n(v.coats)/n(v.coverage)*loss;out.push({label:"Diện tích sơn",value:fmt(area)+" m²"},{label:"Sơn lót",value:fmt(area/n(v.coverage)*loss)+" lít"},{label:"Sơn phủ",value:fmt(liters)+" lít"},{label:"Bột bả (tham khảo)",value:fmt(area*1.2,0)+" kg"});return {primary:area,out}}
   const area=n(v.length)*n(v.width)*q*loss,tile=n(v.tileW)*n(v.tileH);out.push({label:"Diện tích mua",value:fmt(area)+" m²"},{label:"Số viên gạch",value:Math.ceil(area/tile)+" viên"},{label:"Keo dán gạch",value:fmt(area*5,0)+" kg"});return {primary:area,out}
  }
  const total=primary*loss;if(concreteIds.has(item)){const m=mixes[grade];out.push({label:item==="blinding"?"Bê tông lót có hao hụt":item==="footing"?"Bê tông móng kết cấu có hao hụt":"Bê tông có hao hụt",value:fmt(total)+" m³"},{label:"Xi măng PCB40",value:fmt(total*m.cement,0)+" kg",note:"≈ "+Math.ceil(total*m.cement/50)+" bao 50 kg"},{label:"Cát bê tông",value:fmt(total*m.sand)+" m³"},{label:item==="blinding"?"Đá 4×6":"Đá 1×2",value:fmt(total*m.stone)+" m³"},{label:"Nước trộn",value:fmt(total*m.water,0)+" lít"})}
  if(item==="floorBase"){out.push({label:"Ba ta nền có hao hụt",value:fmt(total)+" m³"},{label:"Xi măng PCB30",value:fmt(total*191,0)+" kg"},{label:"Cát bê tông",value:fmt(total*.548)+" m³"},{label:"Đá 4×6 quy đổi",value:fmt(total*.893)+" m³"},{label:"Nước",value:fmt(total*162,0)+" lít"})}
  return {primary,out};
 },[item,footingType,v,grade]);
 const areaItems=["masonry","plaster","wallTile","paint"].includes(item);
 const requiredKeys:Record<ItemId,string[]>={blinding:["length","width","thickness"],footing:footingType==="isolated"?["bottomA","bottomB","topA","topB","totalH","baseH"]:footingType==="stepped"?["bottomA","bottomB","topA","topB","baseH","upperH"]:footingType==="strip"?["length","bottomB","topB","totalH","baseH"]:footingType==="raft"?["length","width","thickness"]:footingType==="pile"?["length","width","height","pileDiameter","pileLength","pileCount"]:["length","width","height"],pedestal:["length","width","height"],gradeBeam:["length","width","height"],column:["length","width","height"],beam:["length","width","height"],slab:["length","width","thickness"],stair:["stairWidth","rise","tread","steps","waist"],floorBase:["length","width","thickness"],masonry:["length","height","thickness"],plaster:["length","height","thickness","sides"],floorTile:["length","width","tileW","tileH"],wallTile:["length","height","tileW","tileH"],paint:["length","height","coverage","coats","sides"]};
 let validationMessage=[...requiredKeys[item],"qty"].some(key=>n(v[key])<=0||n(v[key])>1_000_000)?"Vui lòng nhập kích thước, số lượng và định mức lớn hơn 0 (tối đa 1.000.000).":"";
 if (!validationMessage && item==="footing" && ["isolated","strip"].includes(footingType) && (n(v.baseH)>n(v.totalH)||n(v.topB)>n(v.bottomB)||(footingType==="isolated"&&n(v.topA)>n(v.bottomA)))) validationMessage="Kích thước mặt trên không được vượt quá đáy; chiều dày bản đế không được vượt tổng chiều cao.";
 const activeGroup=groups.find(group=>group.items.some(([id])=>id===item))!;
 const activeFootingName=footingTypes.find(([id])=>id===footingType)?.[1];
 const desktopMenu=<aside className="sticky top-[84px] hidden max-h-[calc(100dvh-96px)] overflow-y-auto rounded-2xl border border-[#dfe7ef] bg-white p-3 shadow-sm lg:block">
  <div className="mb-3 flex items-center gap-2.5 rounded-xl bg-[#073b74] p-3 text-white"><span className="grid size-8 place-items-center rounded-full bg-white/15 font-extrabold">1</span><div><small className="font-bold text-[#bde7f8]">BƯỚC ĐẦU TIÊN</small><h2 className="text-sm font-extrabold">Chọn công tác</h2></div></div>
  {groups.map(group=><div key={group.title} className="mb-4 last:mb-0"><p className="px-2 pb-1.5 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#98a2b3]">{group.title}</p><div className="space-y-1">{group.items.map(([id,label])=><button type="button" key={id} onClick={()=>chooseItem(id)} className={`group flex w-full items-center justify-between rounded-lg px-2.5 py-2 text-left text-[13px] font-semibold ${item===id?"bg-[#e8f6fc] text-[#168ac0]":"text-[#475467] hover:bg-[#f5f7f9]"}`}><span>{label}</span><ChevronRight size={14}/></button>)}</div></div>)}
 </aside>;
 const mobileMenu=<section className="lg:hidden"><div className="mb-2 flex justify-between"><b className="text-xs uppercase tracking-wider text-[#667085]">Chọn hạng mục</b><span className="text-xs font-bold text-[#168ac0]">{activeGroup.title}</span></div><div className="flex max-w-full gap-2 overflow-x-auto pb-2 scrollbar-none">{groups.flatMap(group=>group.items).map(([id,label])=><button type="button" key={id} onClick={()=>chooseItem(id)} className={`shrink-0 rounded-full border px-4 py-2.5 text-sm font-bold ${item===id?"border-[#229ed9] bg-[#229ed9] text-white":"border-[#dfe7ef] bg-white text-[#475467]"}`}>{label}</button>)}</div></section>;
 const resultPanel=<section data-material-results className="overflow-hidden rounded-2xl border border-[#c9d9e8] bg-white shadow-[0_8px_30px_rgba(7,59,116,.09)]"><div className="bg-[#0b4f88] p-4 text-white"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Calculator size={21}/></span><div><p className="text-[10px] font-bold tracking-wider text-[#bde7f8]">BƯỚC 4 · KẾT QUẢ</p><h2 className="text-lg font-extrabold">Phiếu dự trù vật tư</h2></div></div><p className="mt-3 text-sm text-white/75">{item==="footing"?activeFootingName:names[item]}</p></div><div className="p-3"><div className="overflow-hidden rounded-xl border"><div className="divide-y">{validationMessage && <p role="alert" className="p-3 text-sm font-semibold text-rose-700">{validationMessage}</p>}{(validationMessage ? [] : results.out).map((row,index)=><div key={row.label} className={`grid grid-cols-[minmax(0,1fr)_auto] gap-3 px-3 py-2.5 ${index===0?"bg-[#eef9fd]":index%2===0?"bg-[#fbfcfd]":"bg-white"}`}><span className="text-sm font-semibold text-[#475467]">{row.label}</span><span className="text-right text-sm"><b className="block">{row.value}</b>{row.note&&<small className="text-[#667085]">{row.note}</small>}</span></div>)}</div></div><p className="mt-2 rounded-lg bg-[#f5f7f9] p-2.5 text-xs leading-5 text-[#667085]">Dự trù sơ bộ; nghiệm thu phải theo hồ sơ thiết kế và quy cách thực tế.</p></div></section>;
 return <div className="grid items-start justify-center gap-5 lg:grid-cols-[220px_minmax(0,700px)] xl:grid-cols-[220px_minmax(0,700px)_320px]">
  {desktopMenu}
  <div className="min-w-0 space-y-4">
   <section className="rounded-2xl border border-[#dfe7ef] bg-white px-5 py-4 shadow-sm"><p className="text-xs font-extrabold tracking-[.12em] text-[#168ac0]"><EditableText contentKey="calculator.eyebrow">DỰ TOÁN VẬT TƯ</EditableText></p><h1 className="mt-1 text-2xl font-extrabold tracking-[-.035em] text-[#182230]"><EditableText contentKey="calculator.title">Tính khối lượng và vật tư xây dựng</EditableText></h1><p className="mt-1.5 text-sm leading-6 text-[#667085]"><EditableText contentKey="calculator.description">Chọn công tác, nhập kích thước thực tế và nhận bảng vật liệu tương ứng.</EditableText></p></section>
   {mobileMenu}
   <section className="flex flex-col gap-3 rounded-2xl border border-[#dfe7ef] bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#e8f6fc] font-extrabold text-[#168ac0]">2</span><div><p className="text-xs font-bold uppercase tracking-wider text-[#168ac0]">{activeGroup.title}</p><h2 className="mt-1 text-xl font-extrabold tracking-[-.025em] text-[#182230]">{names[item]}</h2><p className="mt-0.5 text-xs text-[#667085]">Nhập kích thước thực tế để lập bảng dự trù.</p></div></div><span className="w-fit rounded-full bg-[#f0f4f8] px-3 py-1.5 text-xs font-bold text-[#52677f]">Tự động quy đổi đơn vị</span></section>
   <section className="rounded-2xl border border-[#dfe7ef] bg-white shadow-sm"><div className="border-b px-4 py-3"><div className="flex gap-3"><span className="grid size-8 place-items-center rounded-full bg-[#f0f4f8] font-extrabold text-[#52677f]">3</span><div><h3 className="font-extrabold text-[#182230]">Thông số đo bóc</h3><p className="text-xs text-[#667085]">Điền các kích thước của hạng mục.</p></div></div></div><div className="p-4">{item==="footing"&&<div className="mb-4 rounded-xl border border-[#dcebf3] bg-[#f5fbfe] p-3"><label><span className="mb-2 block text-sm font-extrabold text-[#182230]">Loại móng</span><select value={footingType} onChange={e=>setFootingType(e.target.value as FootingType)} className="h-10 w-full rounded-lg border bg-white px-3 text-sm font-semibold">{footingTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><FootingPreview type={footingType}/><p className="mt-3 rounded-lg border border-[#b9e2f2] bg-white px-3 py-2 text-xs leading-5 text-[#356078]"><b>Phạm vi tính:</b> chỉ tính đúng hình thể móng đã chọn. Không bao gồm bê tông lót, cổ cột, giằng móng hoặc cấu kiện không thể hiện trên hình.</p></div>}<div className="grid gap-x-4 gap-y-3 sm:grid-cols-2"><StandardFields item={item} footingType={footingType} v={v} set={set}/><Field label={areaItems?"Số khu vực":"Số lượng cấu kiện"} k="qty" v={v} set={set} unit="cái" step="1"/><Field label="Hao hụt dự kiến" k="waste" v={v} set={set} unit="%"/></div>
    {concreteIds.has(item)&&<div className="mt-4 rounded-xl border border-[#dcebf3] bg-[#f5fbfe] p-4"><label><span className="mb-2 block text-sm font-extrabold">Cấp phối bê tông</span><select value={grade} onChange={e=>setGrade(e.target.value as keyof typeof mixes)} className="h-9 w-full rounded-lg border bg-white px-3.5 font-semibold">{item==="blinding"?<><option value="M100">M100 · PCB40 · đá 4×6</option><option value="M150">M150 · PCB40 · đá 4×6</option></>:<><option value="M200">M200 · PCB40 · đá 1×2</option><option value="M250">M250 · PCB40 · đá 1×2</option><option value="M300">M300 · PCB40 · đá 1×2</option></>}</select></label></div>}
    {(item==="masonry"||item==="plaster")&&<p className="mt-4 rounded-xl border border-[#f2dfb6] bg-[#fff9ea] p-4 text-sm leading-6 text-[#7a5612]"><b>Hệ số dự trù:</b> hiệu chỉnh theo loại gạch, mác vữa và cấp phối thực tế.</p>}</div>
   </section>
   <div className="xl:hidden">{resultPanel}</div>
   <section className="rounded-2xl border bg-white p-4 text-xs leading-6 text-[#52677f]"><b className="text-[#182230]">Lưu ý kỹ thuật:</b> Cấp phối trong công cụ là hệ số dự trù tham khảo; cần hiệu chỉnh theo hồ sơ thiết kế và vật liệu thực tế. Hao hụt và định mức có thể thay đổi theo sản phẩm, thiết kế và điều kiện thi công.</section>
  </div>
  <aside className="sticky top-[84px] hidden xl:block">{resultPanel}</aside>
 </div>
}
