"use client";
/* eslint-disable @next/next/no-img-element -- Portfolio images are supplied by freelancers on arbitrary hosts. */


import { useEffect, useState } from 'react';
import { ClientNavigationLink as Link } from '@/components/client-navigation-link';
import { ArrowLeft, ArrowUpRight, BriefcaseBusiness, CircleCheck, ExternalLink, FileText, Layers3, LoaderCircle, MapPin, PencilRuler } from 'lucide-react';
import { MemberAvatar } from '@/components/member-avatar';
import { RequestActionButton } from '@/components/interactive-actions';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { freelanceMoney, type FreelanceActor, type FreelanceProfile } from '@/lib/freelance-types';
import { FreelanceProfileForm, freelanceFetch } from './freelance-ui';

export function FreelanceProfilePage({ id }: { id: string }) {
  const [profile, setProfile] = useState<FreelanceProfile | null>(null), [actor, setActor] = useState<FreelanceActor | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [editing, setEditing] = useState(false), [coverFailed, setCoverFailed] = useState(false);
  useEffect(() => {
    const controller = new AbortController();
    freelanceFetch<{profile: FreelanceProfile; actor: FreelanceActor | null}>('/api/freelance/profiles?id=' + encodeURIComponent(id), { signal: controller.signal }).then(data => { setProfile(data.profile); setActor(data.actor); }).catch(cause => { if (!controller.signal.aborted) setError(cause.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [id]);
  if (loading) return <main className="fm-page"><div className="fm-shell fm-loading"><LoaderCircle className="animate-spin"/><p>Đang mở hồ sơ freelancer…</p></div></main>;
  if (!profile) return <main className="fm-page"><div className="fm-shell fm-empty"><UsersPlaceholder/><h1>Chưa thể mở hồ sơ</h1><p role="alert">{error}</p><Link className="fm-button" href="/thue-thiet-ke">Tìm freelancer khác</Link></div></main>;
  return <main className="fm-page"><div className="fm-shell fm-room-shell"><div className="fm-breadcrumb"><Link href="/thue-thiet-ke"><ArrowLeft size={16}/>Tìm freelancer</Link><span>/</span><span>Hồ sơ chuyên môn</span></div><section className="fm-profile-hero"><div className="fm-profile-cover">{profile.cover && !coverFailed ? <img src={profile.cover} alt={'Công trình của ' + profile.name} referrerPolicy="no-referrer" onError={() => setCoverFailed(true)}/> : <div className="fm-profile-cover-placeholder"><PencilRuler size={58}/><span>THIẾT KẾ BẮT ĐẦU TỪ CON NGƯỜI.</span></div>}</div><div className="fm-profile-intro"><MemberAvatar name={profile.name} className="size-24 border-4 border-white text-4xl"/><div><p className="fm-eyebrow">FREELANCER THIẾT KẾ XÂY DỰNG</p><h1>{profile.name}</h1><p>{profile.title}</p><div className="fm-project-meta">{profile.location && <span><MapPin size={15}/>{profile.location}</span>}<span><Layers3 size={15}/>{profile.experience} năm kinh nghiệm</span><span><CircleCheck size={15}/>{profile.completedCount} dự án hoàn thành</span></div></div>{actor?.id === profile.id && <button className="fm-button fm-button-outline" onClick={() => setEditing(true)}>Sửa hồ sơ<ArrowUpRight size={16}/></button>}</div></section>
    <div className="fm-room-grid fm-profile-grid"><div><section className="fm-panel"><h2>Về tôi & cách tôi làm việc</h2><p className="fm-prose">{profile.bio}</p><h3>Kỹ năng & công cụ</h3><div className="fm-person-tags">{profile.skills.length ? profile.skills.map(skill => <span key={skill}>{skill}</span>) : <p className="fm-muted">Freelancer chưa bổ sung kỹ năng.</p>}</div></section><section className="fm-panel fm-portfolio-panel"><div className="fm-panel-heading"><h2>Công trình tiêu biểu</h2><span>{profile.portfolio.length} công trình</span></div>{profile.portfolio.length ? <div className="fm-portfolio-list">{profile.portfolio.map((work,index) => <a key={work.url + index} href={work.url} target="_blank" rel="noopener noreferrer"><span>0{index + 1}</span><div><h3>{work.title}</h3><small>{new URL(work.url).hostname}</small></div><ExternalLink size={18}/></a>)}</div> : <div className="fm-empty fm-empty-compact"><FileText size={27}/><p>Freelancer sẽ bổ sung công trình tiêu biểu tại đây.</p></div>}</section></div><aside className="fm-room-sidebar"><section className="fm-panel fm-profile-contact"><p className="fm-eyebrow">ĐƠN GIÁ THAM KHẢO</p><strong>{profile.rate ? freelanceMoney(profile.rate) : 'Trao đổi theo nhu cầu'}</strong>{profile.rate > 0 && <p className="fm-muted">/ {profile.rateUnit === 'm2' ? 'm²' : 'dự án'}</p>}<div className="fm-availability"><span className={profile.available ? 'available' : ''}/>{profile.available ? 'Đang nhận dự án mới' : 'Cần trao đổi lịch nhận việc'}</div><hr/><p><BriefcaseBusiness size={17}/>{profile.specialty}</p>{actor?.id !== profile.id && <RequestActionButton requestType="direct-message" targetType="profile" targetId={profile.id} recipientUserId={profile.id} label="Trao đổi nhu cầu" title={'Trao đổi thiết kế với ' + profile.name} description="Chia sẻ yêu cầu công trình, phạm vi công việc và thời gian dự kiến của bạn." allowFile className="fm-button"/>}<Link className="fm-button fm-button-outline" href={'/thue-thiet-ke?create=project&specialty=' + encodeURIComponent(profile.specialty)}>Đăng dự án cùng chuyên môn<ArrowUpRight size={16}/></Link><small>Đơn giá do freelancer cung cấp. Thống nhất báo giá theo phạm vi thực tế của dự án.</small></section></aside></div>
    <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="fm-dialog"><DialogHeader><DialogTitle>Cập nhật hồ sơ freelancer</DialogTitle></DialogHeader><FreelanceProfileForm profile={profile} onSaved={value => { setProfile(value); setCoverFailed(false); setEditing(false); }}/></DialogContent></Dialog>
  </div></main>;
}
function UsersPlaceholder() { return <PencilRuler size={35}/>; }
