"use client";

import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react';
import { ClientNavigationLink as Link } from '@/components/client-navigation-link';
import { useSearchParams } from 'next/navigation';
import { RequestActionButton } from '@/components/interactive-actions';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CircleCheck, Clock3, FileText, Layers3, LoaderCircle, MapPin, MessageSquare, RefreshCw, Send, Users } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { MemberAvatar } from '@/components/member-avatar';
import { freelanceDate, freelanceMoney, type FreelanceRoom, type FreelanceProposal } from '@/lib/freelance-types';
import { FreelanceBadge, FreelanceFiles, FreelanceUpload, freelanceFetch, freelancePost } from './freelance-ui';

export function FreelanceProjectPage({ id }: { id: string }) {
  const params = useSearchParams();
  const [room, setRoom] = useState<FreelanceRoom | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [tab, setTab] = useState<'brief' | 'proposals' | 'work'>(params.get('action') === 'proposals' ? 'proposals' : 'brief');
  const [panel, setPanel] = useState<'proposal' | 'hire' | 'complete' | 'cancel' | null>(null), [chosen, setChosen] = useState<FreelanceProposal | null>(null);
  const [message, setMessage] = useState(''), [messageError, setMessageError] = useState('');
  const [panelError, setPanelError] = useState('');
  const [notice, setNotice] = useState('');
  const [requestedActionHandled, setRequestedActionHandled] = useState(false);
  const contentPanel = useRef<HTMLDivElement>(null);
  const requestId = useRef<string | null>(null);
  const messageId = useRef<string | null>(null);
  const refresh = useCallback(async (signal?: AbortSignal) => {
    const data = await freelanceFetch<FreelanceRoom>('/api/freelance/projects?id=' + encodeURIComponent(id), { signal });
    if (!signal?.aborted) { setRoom(data); setError(''); }
  }, [id]);
  useEffect(() => {
    const controller = new AbortController();
    void freelanceFetch<FreelanceRoom>('/api/freelance/projects?id=' + encodeURIComponent(id), { signal: controller.signal }).then(data => { if (!controller.signal.aborted) setRoom(data); }).catch(cause => { if (!controller.signal.aborted) setError(cause.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    const timer = window.setInterval(() => { if (!document.hidden) void refresh(controller.signal).catch(() => {}); },10000);
    return () => { controller.abort(); window.clearInterval(timer); };
  }, [id, refresh]);
  function openTab(next: typeof tab) {
    setTab(next);
    // On phones the summary is above the tabs; keep the selected content visible.
    contentPanel.current?.scrollIntoView({ block: 'start', inline: 'nearest' });
    contentPanel.current?.focus({ preventScroll: true });
  }
  async function action(name: string, fields: Record<string, unknown> = {}) {
    if (busy) return false; setBusy(true); setPanelError(''); setError('');
    try {
      await freelancePost('/api/freelance/projects', { action: name, id, ...fields });
      setPanel(null); setRequestedActionHandled(true);
      if (name === 'propose') { openTab('proposals'); setNotice('Đã gửi báo giá. Người thuê có thể xem đề xuất và liên hệ với bạn.'); }
      if (name === 'hire') { openTab('work'); setNotice('Đã chọn cộng sự. Hai bên có thể trao đổi và bàn giao trong dự án.'); }
      try { await refresh(); } catch { setError('Đã lưu thao tác. Chưa tải được dữ liệu mới, hãy bấm Cập nhật dự án.'); }
      return true;
    }
    catch (cause) { const text = cause instanceof Error ? cause.message : 'Không thể cập nhật dự án.'; setPanelError(text); setError(text); return false; }
    finally { setBusy(false); }
  }
  function showPanel(value: typeof panel) { requestId.current = null; setPanelError(''); setRequestedActionHandled(true); setPanel(value); }
  async function propose(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const fields = new FormData(event.currentTarget); requestId.current ||= crypto.randomUUID();
    await action('propose', { requestId: requestId.current, price: Number(fields.get('price')), days: Number(fields.get('days')), content: fields.get('content') });
  }
  async function sendMessage(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy || !message.trim()) return; setBusy(true); setMessageError(''); messageId.current ||= crypto.randomUUID();
    try {
      await freelancePost('/api/freelance/projects', { action: 'message', id, requestId: messageId.current, content: message });
      setMessage(''); messageId.current = null;
      try { await refresh(); } catch { setMessageError('Đã gửi trao đổi. Chưa tải được tin mới, hãy bấm Cập nhật dự án.'); }
    }
    catch (cause) { setMessageError(cause instanceof Error ? cause.message : 'Không thể gửi trao đổi.'); }
    finally { setBusy(false); }
  }
  if (loading) return <main className="fm-page"><div className="fm-shell fm-loading"><LoaderCircle className="animate-spin"/><p>Đang mở dự án…</p></div></main>;
  if (!room) return <main className="fm-page"><div className="fm-shell fm-empty"><FileText size={35}/><h1>Chưa thể mở dự án</h1><p role="alert">{error}</p><Link className="fm-button" href="/thue-thiet-ke?view=projects">Khám phá dự án mới</Link></div></main>;
  const { project, actor, profile, proposals, files, messages } = room;
  const owner = actor?.id === project.ownerId, freelancer = actor?.id === project.freelancerId, participant = owner || freelancer;
  const myProposal = proposals.find(proposal => proposal.freelancerId === actor?.id);
  const activePanel = panel || (!requestedActionHandled && params.get('action') === 'proposal' && actor && !owner && profile && project.status === 'open' ? 'proposal' : null);
  const working = ['working','delivered'].includes(project.status);
  const stage = project.status === 'open' ? 0 : project.status === 'working' ? 1 : project.status === 'delivered' ? 2 : 3;
  return <main className="fm-page"><div className="fm-shell fm-room-shell">
    <div className="fm-breadcrumb"><Link href="/thue-thiet-ke?view=projects"><ArrowLeft size={16}/>Sàn thiết kế</Link><span>/</span><span>Dự án</span><button aria-label="Cập nhật dự án" onClick={() => void refresh().catch(cause => setError(cause.message))}><RefreshCw size={16}/></button></div>
    <header className="fm-room-header"><div><p className="fm-eyebrow">{project.specialty}</p><h1>{project.title}</h1><div className="fm-project-meta"><span><MemberAvatar name={project.ownerName} className="size-6 text-xs"/>{project.ownerName}</span><span><MapPin size={14}/>{project.location || 'Làm việc trực tuyến'}</span><span>Đăng ngày {freelanceDate(project.createdAt)}</span></div></div><FreelanceBadge status={project.status}/></header>
    {error && <p className="fm-error" role="alert">{error}</p>}
    <div className="fm-room-grid"><div ref={contentPanel} tabIndex={-1} className="fm-room-content">
      {notice && <p className="fm-notice" role="status">{notice}</p>}
      <nav className="fm-tabs fm-room-tabs" aria-label="Nội dung dự án"><button className={tab === 'brief' ? 'active' : ''} onClick={() => openTab('brief')}><FileText size={16}/>Yêu cầu dự án</button>{actor && <button className={tab === 'proposals' ? 'active' : ''} onClick={() => openTab('proposals')}><Users size={16}/>{owner ? 'Đề xuất nhận được' : 'Đề xuất của tôi'}{owner && <span>{project.proposalCount}</span>}</button>}{participant && project.status !== 'open' && <button className={tab === 'work' ? 'active' : ''} onClick={() => openTab('work')}><MessageSquare size={16}/>Không gian làm việc</button>}</nav>
      {tab === 'brief' && <section className="fm-panel"><h2>Điều bên thuê đang tìm kiếm</h2><p className="fm-prose">{project.description || 'Bên thuê sẽ bổ sung chi tiết qua tài liệu và trao đổi về đề xuất của bạn.'}</p><div className="fm-brief-details"><div><small>Chuyên môn</small><b>{project.specialty}</b></div><div><small>Thời gian dự kiến</small><b>{project.days ? project.days + ' ngày' : 'Thống nhất theo đề xuất'}</b></div></div><h3>Tài liệu đầu vào</h3><FreelanceFiles files={files.filter(file => file.purpose === 'brief')}/>{!files.some(file => file.purpose === 'brief') && <p className="fm-muted">{actor ? 'Chưa có tài liệu đính kèm.' : 'Đăng nhập để xem tài liệu dự án.'}</p>}{owner && project.status === 'open' && <FreelanceUpload projectId={id} purpose="brief" onUploaded={refresh}/>}</section>}
      {tab === 'proposals' && <section className="fm-panel"><h2>{owner ? 'Chọn cộng sự qua đề xuất' : 'Phương án bạn đề xuất'}</h2><p className="fm-muted">{owner ? 'So sánh cách tiếp cận, chi phí và thời gian trước khi chọn người thực hiện.' : 'Mô tả cách thực hiện và hồ sơ bạn sẽ bàn giao. Đề xuất chỉ hiển thị với bạn và bên thuê.'}</p>{proposals.length ? <div className="fm-proposals">{proposals.map(proposal => <article key={proposal.id} className="fm-proposal"><div className="fm-proposal-top"><Link href={'/thue-thiet-ke/freelancer/' + encodeURIComponent(proposal.freelancerId)}><MemberAvatar name={proposal.name} className="size-11"/><span><b>{proposal.name}</b><small>{proposal.title}</small></span></Link><strong>{freelanceMoney(proposal.price)}<small>{proposal.days} ngày thực hiện</small></strong></div><p className="fm-prose">{proposal.content}</p><div className="fm-proposal-footer"><small>Gửi ngày {freelanceDate(proposal.createdAt)}</small>{owner && project.status === 'open' && <RequestActionButton requestType="direct-message" targetType="profile" targetId={proposal.freelancerId} recipientUserId={proposal.freelancerId} label="Trao đổi báo giá" title={'Trao đổi báo giá với ' + proposal.name} description={'Dự án: ' + project.title} allowFile className="fm-button fm-button-small fm-button-outline"/>}{owner && project.status === 'open' && <button className="fm-button fm-button-small" onClick={() => { setChosen(proposal); showPanel('hire'); }}>Chọn cộng sự<ArrowRight size={15}/></button>}{!owner && project.status === 'open' && <button className="fm-button fm-button-small fm-button-outline" onClick={() => showPanel('proposal')}>Sửa đề xuất</button>}{project.freelancerId === proposal.freelancerId && <span className="fm-selected"><Check size={15}/>Đã được chọn</span>}</div></article>)}</div> : <div className="fm-empty fm-empty-compact"><Users size={30}/><h3>{owner ? 'Đang chờ những đề xuất đầu tiên' : 'Giới thiệu cách bạn sẽ làm dự án này'}</h3><p>{owner ? 'Freelancer có thể tìm và gửi đề xuất từ danh sách dự án.' : 'Một đề xuất rõ ràng sẽ giúp bên thuê hiểu chuyên môn của bạn.'}</p></div>}</section>}
      {tab === 'work' && participant && project.status !== 'open' && <div className="fm-workspace"><section className="fm-panel"><div className="fm-panel-heading"><h2>Hồ sơ bàn giao</h2><span><Layers3 size={17}/></span></div><FreelanceFiles files={files.filter(file => file.purpose === 'delivery')}/>{!files.some(file => file.purpose === 'delivery') && <p className="fm-muted">Freelancer sẽ gửi hồ sơ hoàn thiện tại đây.</p>}{freelancer && project.status === 'working' && <><FreelanceUpload projectId={id} purpose="delivery" onUploaded={refresh}/><button className="fm-button" disabled={busy} onClick={() => void action('deliver')}>Gửi xác nhận bàn giao<ArrowRight size={16}/></button></>}{owner && project.status === 'delivered' && <div className="fm-work-actions"><button className="fm-button" disabled={busy} onClick={() => showPanel('complete')}><CircleCheck size={17}/>Xác nhận hoàn thành</button><button className="fm-button fm-button-outline" disabled={busy} onClick={() => void action('revise')}>Yêu cầu điều chỉnh</button></div>}</section><section className="fm-panel"><h2>Trao đổi trong dự án</h2><p className="fm-muted">Không gian riêng của bên thuê và freelancer được chọn.</p><div className="fm-discussion" aria-live="polite">{messages.length ? messages.map(item => <article key={item.id} className={item.authorId === actor?.id ? 'own' : ''}><div><b>{item.authorName}</b><small>{freelanceDate(item.createdAt)}</small></div><p className="fm-prose">{item.content}</p></article>) : <div className="fm-discussion-empty"><MessageSquare size={25}/><p>Bắt đầu bằng việc thống nhất bước làm tiếp theo.</p></div>}</div>{working && <form className="fm-composer" onSubmit={sendMessage}><textarea aria-label="Nội dung trao đổi" disabled={busy} value={message} maxLength={4000} rows={3} placeholder="Trao đổi về ý tưởng, tiến độ hoặc phần cần điều chỉnh…" onChange={event => { setMessage(event.target.value); messageId.current = null; }}/>{messageError && <p className="fm-error" role="alert">{messageError}</p>}<button className="fm-button fm-button-small" disabled={busy || !message.trim()}>{busy ? <LoaderCircle size={16} className="animate-spin"/> : <Send size={16}/>}Gửi trao đổi</button></form>}</section></div>}
    </div><aside className="fm-room-sidebar"><section className="fm-panel fm-project-summary"><p className="fm-eyebrow">{project.agreedPrice ? 'ĐỀ XUẤT ĐÃ THỐNG NHẤT' : 'NGÂN SÁCH DỰ KIẾN'}</p><strong>{project.agreedPrice || project.budget ? freelanceMoney(project.agreedPrice || project.budget) : 'Cần tư vấn báo giá'}</strong><div><Clock3 size={16}/>{project.agreedDays || project.days ? (project.agreedDays || project.days) + ' ngày thực hiện' : 'Thời gian cần trao đổi'}</div><div><Users size={16}/>{project.proposalCount} đề xuất</div>{project.status === 'open' && !owner && (actor ? profile ? <button className="fm-button" onClick={() => showPanel('proposal')}>{myProposal ? 'Cập nhật báo giá' : 'Báo giá / nhận việc'}<ArrowUpRight size={16}/></button> : <Link className="fm-button" href={'/thue-thiet-ke?create=profile&return_to=' + encodeURIComponent('/thue-thiet-ke/' + id + '?action=proposal')}>Tạo hồ sơ để nhận việc<ArrowUpRight size={16}/></Link> : <Link className="fm-button" href={'/dang-nhap?return_to=' + encodeURIComponent('/thue-thiet-ke/' + id + '?action=proposal')}>Đăng nhập để báo giá</Link>)}{owner && project.status === 'open' && <button className="fm-button" onClick={() => openTab('proposals')}>Xem đề xuất nhận được<ArrowRight size={16}/></button>}{participant && project.status !== 'open' && <button className="fm-button" onClick={() => openTab('work')}>Mở không gian làm việc<ArrowRight size={16}/></button>}{!owner && project.status === 'open' && (actor ? <RequestActionButton key={id + ':' + params.get('action')} defaultOpen={params.get('action') === 'contact'} requestType="direct-message" targetType="profile" targetId={project.ownerId} recipientUserId={project.ownerId} label="Liên hệ người thuê" title={'Trao đổi dự án: ' + project.title} description={'Người thuê: ' + project.ownerName + '. Bạn có thể hỏi rõ yêu cầu và thống nhất phạm vi trước khi báo giá.'} allowFile className="fm-button fm-button-outline"/> : <Link className="fm-button fm-button-outline" href={'/dang-nhap?return_to=' + encodeURIComponent('/thue-thiet-ke/' + id + '?action=contact')}>Đăng nhập để liên hệ người thuê</Link>)}{owner && project.status === 'open' && <p className="fm-form-hint">Bạn là người đăng dự án. Freelancer sẽ gửi báo giá để bạn xem, trao đổi và chọn người làm.</p>}<p className="fm-form-hint">Chi phí và hồ sơ bàn giao được thống nhất trực tiếp giữa hai bên.</p></section><section className="fm-panel fm-project-progress"><h3>Các bước cùng thực hiện</h3>{['Đăng dự án & nhận đề xuất','Chọn cộng sự & thực hiện','Gửi hồ sơ bàn giao','Xác nhận hoàn thành'].map((label,index) => <div key={label} className={project.status === 'cancelled' ? '' : stage >= index ? 'active' : ''}><span>{stage > index && project.status !== 'cancelled' ? <Check size={13}/> : index + 1}</span><p>{label}</p></div>)}</section>{owner && project.status === 'open' && <button className="fm-close-project" onClick={() => showPanel('cancel')}>Đóng dự án</button>}</aside></div>
    <Dialog open={activePanel !== null} onOpenChange={open => { if (!busy && !open) { setPanel(null); setRequestedActionHandled(true); } }}><DialogContent className="fm-dialog"><DialogHeader><p className="fm-eyebrow">{project.specialty}</p><DialogTitle>{activePanel === 'proposal' ? myProposal ? 'Cập nhật đề xuất của bạn' : 'Gửi đề xuất cho dự án' : activePanel === 'hire' ? 'Chọn cộng sự thực hiện' : activePanel === 'complete' ? 'Xác nhận hồ sơ hoàn thành' : 'Đóng nhận đề xuất'}</DialogTitle></DialogHeader>{activePanel === 'proposal' ? <form className="fm-form" onSubmit={propose}><fieldset disabled={busy}><div className="fm-form-row"><label>Giá trọn gói (VNĐ) <span>*</span><input name="price" type="number" min={1} max={500000000} step={1} required defaultValue={myProposal?.price}/></label><label>Thời gian thực hiện (ngày) <span>*</span><input name="days" type="number" min={1} max={365} step={1} required defaultValue={myProposal?.days || 14}/></label></div><label>Cách thực hiện & hồ sơ bàn giao <span>*</span><textarea name="content" rows={6} maxLength={4000} required defaultValue={myProposal?.content} placeholder="Cách tiếp cận, công việc nhận làm, định dạng hồ sơ và số lần chỉnh sửa…"/></label>{panelError && <p className="fm-error" role="alert">{panelError}</p>}<button className="fm-button" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" size={17}/> : <Send size={17}/>}Gửi đề xuất</button></fieldset></form> : <><p className="fm-prose">{activePanel === 'hire' && chosen ? `Bạn chọn ${chosen.name} thực hiện dự án với giá ${freelanceMoney(chosen.price)} trong ${chosen.days} ngày. Nội dung đề xuất sẽ là phạm vi hai bên cùng thực hiện.` : activePanel === 'complete' ? 'Xác nhận bạn đã kiểm tra và nhận đủ hồ sơ theo đề xuất đã thống nhất. Dự án sẽ được đánh dấu hoàn thành.' : 'Dự án sẽ dừng nhận đề xuất và chuyển sang trạng thái đã đóng.'}</p>{activePanel === 'hire' && chosen && <blockquote className="fm-hire-scope">{chosen.content}</blockquote>}{panelError && <p className="fm-error" role="alert">{panelError}</p>}<button className="fm-button" disabled={busy} onClick={() => void action(activePanel === 'hire' ? 'hire' : activePanel === 'complete' ? 'complete' : 'cancel', activePanel === 'hire' ? { proposalId: chosen?.id } : {})}>{busy ? <LoaderCircle size={17} className="animate-spin"/> : <Check size={17}/>} {activePanel === 'hire' ? 'Chọn & bắt đầu dự án' : activePanel === 'complete' ? 'Xác nhận hoàn thành' : 'Đóng dự án'}</button></>}</DialogContent></Dialog>
  </div></main>;
}
