"use client";
/* eslint-disable @next/next/no-img-element -- Portfolio images are supplied by freelancers on arbitrary hosts. */


import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ClientNavigationLink as Link } from '@/components/client-navigation-link';
import { safeAuthReturn } from '@/lib/auth-return';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowDown, ArrowRight, ArrowUpRight, BriefcaseBusiness, Building2, Check, ChevronLeft, ChevronRight, CircleCheck, ClipboardList, FileText, HardHat, Layers3, LoaderCircle, MapPin, MessageSquare, PencilRuler, Plus, Search, SlidersHorizontal, Sofa, Users, X, Zap } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { MemberAvatar } from '@/components/member-avatar';
import { freelanceSpecialties, freelanceMoney, type FreelanceListing, type FreelanceProfile, type FreelanceProject } from '@/lib/freelance-types';
import { FreelanceBadge, FreelanceProfileForm, freelanceFetch, freelancePost } from './freelance-ui';

const services = [
  { icon: Building2, name: 'Kiến trúc', description: 'Từ ý tưởng đến ngôi nhà' },
  { icon: HardHat, name: 'Kết cấu', description: 'Vững chắc từ nền móng' },
  { icon: Sofa, name: 'Nội thất', description: 'Không gian mang dấu ấn' },
  { icon: Zap, name: 'Điện nước', description: 'Hệ thống vận hành tốt' },
  { icon: ClipboardList, name: 'Dự toán', description: 'Chủ động chi phí xây dựng' },
  { icon: PencilRuler, name: 'Bản vẽ kỹ thuật', description: 'Chi tiết để thi công' },
];
type View = 'freelancers' | 'projects' | 'mine';
const headings: Record<View, string> = { freelancers: 'Tìm cộng sự cho ý tưởng của bạn', projects: 'Dự án đang tìm người thiết kế', mine: 'Không gian làm việc của bạn' };
const emptyListing: FreelanceListing = { profiles: [], projects: [], total: 0, page: 1, actor: null, profile: null };

export function FreelanceMarketplace() {
  const router = useRouter(), params = useSearchParams();
  const paramView = params.get('view'), view: View = paramView === 'projects' || paramView === 'mine' ? paramView : 'freelancers';
  const [listing, setListing] = useState(emptyListing), [page, setPage] = useState(1);
  const [query, setQuery] = useState(''), [specialty, setSpecialty] = useState((freelanceSpecialties as readonly string[]).includes(params.get('specialty') || '') ? params.get('specialty')! : ''), [available, setAvailable] = useState(false), [budget, setBudget] = useState(''), [sort, setSort] = useState('recent');
  const [loading, setLoading] = useState(true), [loadError, setLoadError] = useState(''), [revision, setRevision] = useState(0);
  const [filtersOpen, setFiltersOpen] = useState(false), [dialog, setDialog] = useState<'project' | 'profile' | null>(null), [busy, setBusy] = useState(false), [submitError, setSubmitError] = useState('');
  const requestId = useRef<string | null>(null), resultRef = useRef<HTMLElement>(null);
  const isFreelancers = view === 'freelancers';
  const hasFilters = Boolean(query || specialty || (isFreelancers ? available : budget));
  const { actor, profile, total } = listing;
  const activeSort = isFreelancers ? ['recent', 'experience', 'rate'].includes(sort) ? sort : 'recent' : ['recent', 'budget-desc', 'budget-asc'].includes(sort) ? sort : 'recent';

  useEffect(() => {
    const controller = new AbortController();
    const timer = window.setTimeout(() => {
      setLoading(true); setLoadError('');
      const search = new URLSearchParams({ view, q: query, specialty, budget, available: available ? '1' : '0', page: String(page), sort: activeSort });
      freelanceFetch<FreelanceListing>('/api/freelance?' + search, { signal: controller.signal })
        .then(data => { if (!controller.signal.aborted) setListing(data); })
        .catch(cause => { if (!controller.signal.aborted) setLoadError(cause.message); })
        .finally(() => { if (!controller.signal.aborted) setLoading(false); });
    }, 180);
    return () => { controller.abort(); window.clearTimeout(timer); };
  }, [view, query, specialty, available, budget, activeSort, page, revision]);

  function switchView(next: View) {
    if (next === 'mine' && !actor) { router.push('/dang-nhap?return_to=' + encodeURIComponent('/thue-thiet-ke?view=mine')); return; }
    setLoading(true); setPage(1); setSort('recent'); setSpecialty(''); setQuery(''); setFiltersOpen(false);
    router.replace(next === 'freelancers' ? '/thue-thiet-ke' : '/thue-thiet-ke?view=' + next, { scroll: false });
  }
  function openDialog(next: 'project' | 'profile') {
    if (!actor) { router.push('/dang-nhap?return_to=' + encodeURIComponent('/thue-thiet-ke?create=' + next)); return; }
    requestId.current = null; setSubmitError(''); setDialog(next);
  }
  function profileSaved() {
    setDialog(null); setRevision(value => value + 1);
    const returnTo = safeAuthReturn(params.get('return_to'), '/thue-thiet-ke');
    if (params.get('create')) router.replace(returnTo.startsWith('/thue-thiet-ke/') ? returnTo : '/thue-thiet-ke', { scroll: true });
  }
  const requestedDialog = params.get('create');
  const activeDialog = dialog || (actor && !loading && (requestedDialog === 'project' || requestedDialog === 'profile') ? requestedDialog : null);
  function closeDialog(open: boolean) { if (busy) return; if (!open) { setDialog(null); if (params.get('create')) router.replace('/thue-thiet-ke', { scroll: false }); } }
  async function postProject(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy) return; setBusy(true); setSubmitError('');
    const fields = new FormData(event.currentTarget); requestId.current ||= crypto.randomUUID();
    try {
      const data = await freelancePost<{ project: FreelanceProject }>('/api/freelance/projects', { action: 'create', requestId: requestId.current, title: fields.get('title'), specialty: fields.get('specialty'), description: fields.get('description'), location: fields.get('location'), budget: Number(fields.get('budget') || 0), days: Number(fields.get('days') || 0) });
      router.push('/thue-thiet-ke/' + data.project.id);
    } catch (cause) { setSubmitError(cause instanceof Error ? cause.message : 'Không thể đăng dự án.'); setBusy(false); }
  }
  function resetFilters() { setQuery(''); setSpecialty(''); setAvailable(false); setBudget(''); setPage(1); }
  function selectService(value: string) { setSpecialty(specialty === value ? '' : value); setPage(1); resultRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }

  return <main className="fm-page"><div className="fm-shell">
    <div className="fm-topline"><span><span className="fm-mark"><PencilRuler size={16}/></span>NhàĐẹpChất <i>/</i> THUÊ THIẾT KẾ</span><button onClick={() => openDialog('profile')} disabled={loading}>{profile ? 'Hồ sơ freelancer của tôi' : 'Trở thành freelancer'}<ArrowUpRight size={15}/></button></div>
    <section className="fm-hero" aria-labelledby="fm-heading"><div className="fm-hero-copy"><p className="fm-eyebrow"><span/>CỘNG SỰ NHỎ. Ý TƯỞNG LỚN.</p><h1 id="fm-heading">Đúng người thiết kế.<br/><em>Đúng ngôi nhà bạn mơ.</em></h1><p>Kết nối với freelancer trong lĩnh vực thiết kế xây dựng.<br className="fm-desktop-break"/> Từ nét phác đầu tiên đến bộ hồ sơ hoàn chỉnh.</p><div className="fm-hero-actions"><button className="fm-button" disabled={loading} onClick={() => openDialog('project')}><Plus size={18}/>Đăng dự án <ArrowUpRight size={17}/></button><button className="fm-text-link" onClick={() => { if (!isFreelancers) switchView('freelancers'); resultRef.current?.scrollIntoView({ behavior: 'smooth' }); }}>Khám phá freelancer <ArrowDown size={16}/></button></div><div className="fm-hero-notes"><span><Check size={15}/>Chuyên môn phù hợp</span><span><Check size={15}/>Báo giá rõ ràng</span><span><Check size={15}/>Làm việc trực tiếp</span></div></div>
    <div className="fm-blueprint" aria-hidden="true"><div className="fm-plan-caption"><span>FROM A SKETCH</span><span>01 / CONCEPT</span></div><div className="fm-house"><div className="fm-house-roof"/><div className="fm-house-upper"><i/><i/><i/></div><div className="fm-house-floor"><i/><i/><i/></div><div className="fm-house-ground"><i/><i/></div><div className="fm-tree"><span/><i/></div></div><span className="fm-dimension fm-dimension-width">5.000</span><span className="fm-dimension fm-dimension-height">+ 9.600</span><div className="fm-plan-card"><span className="fm-plan-icon"><Layers3 size={20}/></span><div><b>Mỗi công trình, một cộng sự.</b><small>Kiến trúc · Kỹ thuật · Nội thất</small></div><span className="fm-plan-check"><Check size={15}/></span></div><div className="fm-plan-footer"><span>TO YOUR SPACE</span><PencilRuler size={16}/></div></div></section>
    <section className="fm-services" aria-label="Khám phá theo chuyên môn">{services.map((service, index) => <button key={service.name} aria-pressed={specialty === freelanceSpecialties[index]} className={specialty === freelanceSpecialties[index] ? 'active' : ''} onClick={() => selectService(freelanceSpecialties[index])}><service.icon size={23}/><b>{service.name}</b><small>{service.description}</small></button>)}</section>

    <section className="fm-market" ref={resultRef} aria-labelledby="fm-results-title"><nav className="fm-tabs" aria-label="Không gian freelancer">{([{ value: 'freelancers', label: 'Tìm freelancer', icon: Users }, { value: 'projects', label: 'Tìm dự án', icon: BriefcaseBusiness }, { value: 'mine', label: 'Dự án của tôi', icon: Layers3 }] as const).map(tab => <button key={tab.value} aria-current={view === tab.value ? 'page' : undefined} className={view === tab.value ? 'active' : ''} onClick={() => switchView(tab.value)}><tab.icon size={17}/>{tab.label}</button>)}<span className="fm-tabs-note">Một nơi để tìm nhau. Một nơi để làm việc.</span></nav>
      <div className="fm-market-layout"><aside className={'fm-sidebar ' + (filtersOpen ? 'fm-filters-open' : '')}><div className="fm-filter-heading"><h2><SlidersHorizontal size={17}/>Bộ lọc tìm kiếm</h2><button className="fm-reset" onClick={resetFilters} disabled={!hasFilters}>Đặt lại</button><button className="fm-close-filter" aria-label="Đóng bộ lọc" onClick={() => setFiltersOpen(false)}><X size={18}/></button></div><fieldset className="fm-filter-group"><legend>Chuyên môn</legend>{['', ...freelanceSpecialties].map(value => <label key={value || 'all'}><input type="radio" name="specialty" checked={specialty === value} onChange={() => { setSpecialty(value); setPage(1); }}/><span>{value || 'Tất cả chuyên môn'}</span></label>)}</fieldset>
        {isFreelancers ? <fieldset className="fm-filter-group"><legend>Khả năng nhận việc</legend><label className="fm-check"><input type="checkbox" checked={available} onChange={event => { setAvailable(event.target.checked); setPage(1); }}/><span>Đang nhận dự án mới</span></label><p>Trao đổi với freelancer để thống nhất lịch bắt đầu.</p></fieldset> : <fieldset className="fm-filter-group"><legend>Ngân sách dự án</legend>{[['', 'Tất cả ngân sách'], ['under-5', 'Dưới 5 triệu'], ['5-20', 'Từ 5 đến 20 triệu'], ['over-20', 'Trên 20 triệu'], ['discuss', 'Cần tư vấn báo giá']].map(([value, label]) => <label key={label}><input type="radio" name="budget" checked={budget === value} onChange={() => { setBudget(value); setPage(1); }}/><span>{label}</span></label>)}</fieldset>}
        <div className="fm-sidebar-help"><span><FileText size={23}/></span><h3>Ý tưởng còn đang phác thảo?</h3><p>Mô tả điều bạn muốn. Để cộng sự giúp bạn hoàn thiện phần còn lại.</p><button className="fm-text-link" disabled={loading} onClick={() => openDialog('project')}>Đăng nhu cầu <ArrowRight size={15}/></button></div>
      </aside><div className="fm-results"><div className="fm-results-heading"><div><p className="fm-eyebrow">{isFreelancers ? 'NGƯỜI ĐỒNG HÀNH CHO CÔNG TRÌNH' : view === 'projects' ? 'CƠ HỘI CHO CHUYÊN MÔN CỦA BẠN' : 'TỪ ĐỀ XUẤT ĐẾN BÀN GIAO'}</p><h2 id="fm-results-title">{headings[view]}</h2></div><span className="fm-result-count" aria-live="polite">{loading ? 'Đang tìm…' : loadError ? 'Chưa tải được' : `${total} ${isFreelancers ? 'freelancer' : 'dự án'}`}</span></div>
        <div className="fm-toolbar"><label className="fm-search"><Search size={19}/><input aria-label={isFreelancers ? 'Tìm freelancer' : 'Tìm dự án'} placeholder={isFreelancers ? 'Tên, kỹ năng, địa điểm…' : 'Dự án, nhu cầu hoặc địa điểm…'} value={query} maxLength={100} onChange={event => { setQuery(event.target.value); setPage(1); }}/>{query && <button aria-label="Xóa tìm kiếm" onClick={() => { setQuery(''); setPage(1); }}><X size={16}/></button>}</label><label className="fm-sort"><span>Sắp xếp</span><select aria-label="Sắp xếp kết quả" value={activeSort} onChange={event => { setSort(event.target.value); setPage(1); }}><option value="recent">Mới nhất</option>{isFreelancers ? <><option value="experience">Nhiều kinh nghiệm</option><option value="rate">Đơn giá thấp nhất</option></> : <><option value="budget-desc">Ngân sách cao nhất</option><option value="budget-asc">Ngân sách thấp nhất</option></>}</select></label><button className="fm-mobile-filter" aria-expanded={filtersOpen} onClick={() => setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={17}/>Bộ lọc</button></div>
        {specialty && <div className="fm-active-filter"><span>{specialty}<button aria-label="Bỏ lọc chuyên môn" onClick={() => { setSpecialty(''); setPage(1); }}><X size={13}/></button></span></div>}
        {loadError ? <div className="fm-empty" role="alert"><FileText size={32}/><h3>Chưa thể tải danh sách</h3><p>{loadError}</p><button className="fm-button fm-button-outline" onClick={() => setRevision(value => value + 1)}>Thử lại</button></div> : loading ? <div className="fm-loading" role="status"><LoaderCircle size={23} className="animate-spin"/><p>Đang tìm {isFreelancers ? 'cộng sự' : 'dự án'} phù hợp…</p></div> : total === 0 ? <div className="fm-empty"><span className="fm-empty-icon">{isFreelancers ? <Users size={30}/> : <BriefcaseBusiness size={30}/>}</span><p className="fm-eyebrow">{hasFilters ? 'MỞ RỘNG TÌM KIẾM CỦA BẠN' : 'MỘT KHỞI ĐẦU MỚI'}</p><h3>{hasFilters ? 'Chưa có kết quả phù hợp' : isFreelancers ? 'Cộng sự đầu tiên có thể là bạn.' : view === 'projects' ? 'Công trình tiếp theo bắt đầu ở đây.' : 'Sẵn sàng cho dự án đầu tiên?'}</h3><p>{hasFilters ? 'Thử từ khóa khác hoặc mở rộng bộ lọc để tìm thêm kết quả.' : isFreelancers ? 'Giới thiệu chuyên môn, chia sẻ công trình và kết nối với những người đang cần bạn.' : view === 'projects' ? 'Chia sẻ nhu cầu của bạn để freelancer gửi đề xuất và báo giá.' : 'Các dự án bạn đăng, gửi đề xuất hoặc nhận thực hiện sẽ xuất hiện tại đây.'}</p>{hasFilters ? <button className="fm-button fm-button-outline" onClick={resetFilters}>Xóa bộ lọc</button> : <button className="fm-button" onClick={() => openDialog(isFreelancers ? 'profile' : 'project')}><Plus size={16}/>{isFreelancers ? 'Tạo hồ sơ freelancer' : 'Đăng dự án đầu tiên'}</button>}<div className="fm-empty-footer"><span><PencilRuler size={16}/>Chuyên môn của bạn</span><i/><span><Building2 size={16}/>Công trình của họ</span></div></div> : isFreelancers ? <div className="fm-freelancer-grid">{listing.profiles.map(person => <FreelancerCard key={person.id} person={person}/>)}</div> : <div className="fm-project-list">{listing.projects.map(project => <ProjectCard key={project.id} project={project} actorId={actor?.id}/>)}</div>}
        {!loading && !loadError && total > 6 && <nav className="fm-pagination" aria-label="Phân trang"><button disabled={page === 1} onClick={() => setPage(value => value - 1)}><ChevronLeft size={16}/>Trước</button><span>Trang {page} / {Math.ceil(total / 6)}</span><button disabled={page * 6 >= total} onClick={() => setPage(value => value + 1)}>Sau<ChevronRight size={16}/></button></nav>}<p className="fm-list-note">{isFreelancers ? 'Hồ sơ do freelancer giới thiệu · Đơn giá tham khảo, thống nhất theo từng dự án.' : 'Chốt phạm vi, chi phí, thời gian và hồ sơ cần nhận trước khi bắt đầu.'}</p>
      </div></div></section>
    <section className="fm-how" aria-labelledby="fm-how-title"><div className="fm-how-heading"><p className="fm-eyebrow">LÀM VIỆC CÙNG NHAU, DỄ HƠN</p><h2 id="fm-how-title">Từ ý tưởng<br/>đến hồ sơ hoàn chỉnh.</h2></div>{[{ title: 'Chia sẻ nhu cầu', text: 'Đăng dự án với chuyên môn, ngân sách và mong muốn của bạn.' }, { title: 'Chọn đúng cộng sự', text: 'Xem hồ sơ, so sánh đề xuất và thống nhất phạm vi công việc.' }, { title: 'Cùng hoàn thiện', text: 'Trao đổi trong dự án, gửi hồ sơ và xác nhận kết quả bàn giao.' }].map((step, index) => <div className="fm-how-step" key={step.title}><span>0{index + 1}</span><h3>{step.title}</h3><p>{step.text}</p></div>)}</section>
    <section className="fm-join"><div><span className="fm-eyebrow">DÀNH CHO NGƯỜI LÀM THIẾT KẾ XÂY DỰNG</span><h2>Chuyên môn của bạn. Công trình tiếp theo.</h2><p>Kiến trúc, kết cấu, nội thất hay một bản vẽ nhỏ — luôn có người cần bạn.</p></div><button className="fm-button fm-button-outline" disabled={loading} onClick={() => openDialog('profile')}>{profile ? 'Cập nhật hồ sơ của tôi' : 'Tham gia cùng NhàĐẹpChất'}<ArrowUpRight size={17}/></button></section>
  </div>
  <Dialog open={activeDialog !== null} onOpenChange={closeDialog}><DialogContent className="fm-dialog"><DialogHeader><p className="fm-eyebrow">{activeDialog === 'profile' ? 'GIỚI THIỆU CHUYÊN MÔN CỦA BẠN' : 'BẮT ĐẦU MỘT CÔNG TRÌNH'}</p><DialogTitle>{activeDialog === 'profile' ? profile ? 'Hồ sơ freelancer của tôi' : 'Tạo hồ sơ freelancer' : 'Đăng dự án thiết kế'}</DialogTitle></DialogHeader>{activeDialog === 'profile' ? <FreelanceProfileForm profile={profile} onSaved={profileSaved}/> : <><p className="fm-dialog-intro">Cho cộng sự tương lai biết bạn cần gì. Bạn có thể bổ sung tài liệu sau khi đăng.</p><form className="fm-form" onSubmit={postProject}><fieldset disabled={busy}><label>Tên dự án <span>*</span><input name="title" required maxLength={140} placeholder="Thiết kế nhà phố 3 tầng, diện tích 5 × 20m"/></label><label>Chuyên môn cần thuê <span>*</span><select name="specialty" defaultValue={specialty || freelanceSpecialties[0]}>{freelanceSpecialties.map(value => <option key={value}>{value}</option>)}</select></label><label>Mô tả nhu cầu <small>Không bắt buộc</small><textarea name="description" rows={4} maxLength={6000} placeholder="Quy mô, phong cách, hồ sơ cần nhận hoặc điều bạn muốn tư vấn…"/></label><div className="fm-form-row"><label>Ngân sách dự kiến (VNĐ)<input name="budget" type="number" min={0} max={500000000} step={1} placeholder="Để trống để nhận báo giá"/></label><label>Thời gian dự kiến (ngày)<input name="days" type="number" min={0} max={365} step={1} placeholder="Để trống để trao đổi"/></label></div><label>Địa điểm công trình<input name="location" maxLength={150} placeholder="Tỉnh/thành hoặc làm việc trực tuyến"/></label><p className="fm-form-hint">Bạn có thể xem và so sánh đề xuất trước khi chọn freelancer.</p>{submitError && <p className="fm-error" role="alert">{submitError}</p>}<button className="fm-button" disabled={busy}>{busy ? <LoaderCircle className="animate-spin" size={17}/> : <Plus size={17}/>} {busy ? 'Đang đăng dự án…' : 'Đăng dự án & nhận đề xuất'}</button></fieldset></form></>}</DialogContent></Dialog>
  </main>;
}

function FreelancerCard({ person }: { person: FreelanceProfile }) {
  const [coverFailed, setCoverFailed] = useState(false);
  const href = '/thue-thiet-ke/freelancer/' + encodeURIComponent(person.id);
  return <article className="fm-freelancer-card"><Link className="fm-work-preview" href={href} aria-label={'Xem hồ sơ ' + person.name}>{person.cover && !coverFailed ? <img src={person.cover} alt={'Công trình đại diện của ' + person.name} loading="lazy" referrerPolicy="no-referrer" onError={() => setCoverFailed(true)}/> : <div className="fm-preview-placeholder"><PencilRuler size={37}/><span>{person.specialty}</span><small>Ý tưởng bắt đầu từ một nét vẽ</small></div>}<span className="fm-work-type">{person.specialty}</span><span className="fm-preview-arrow"><ArrowUpRight size={19}/></span></Link><div className="fm-freelancer-content"><div className="fm-person"><MemberAvatar name={person.name} className="size-12"/><div><Link href={href}><h3>{person.name}</h3></Link><p>{person.title}</p></div></div><div className="fm-availability"><span className={person.available ? 'available' : ''}/>{person.available ? 'Đang nhận dự án' : 'Trao đổi lịch nhận việc'}{person.location && <span className="fm-person-location"><MapPin size={12}/>{person.location}</span>}</div><p className="fm-person-description">{person.bio}</p><div className="fm-person-tags">{person.skills.slice(0,3).map(skill => <span key={skill}>{skill}</span>)}</div><div className="fm-person-stats"><span><Layers3 size={14}/>{person.experience} năm kinh nghiệm</span><span><CircleCheck size={14}/>{person.completedCount} dự án</span></div><div className="fm-card-actions"><div><small>Đơn giá từ</small><b>{person.rate ? freelanceMoney(person.rate) : 'Trao đổi'}{person.rate > 0 && <small> / {person.rateUnit === 'm2' ? 'm²' : 'dự án'}</small>}</b></div><Link href={href} className="fm-button fm-button-small fm-button-outline">Xem hồ sơ<ArrowUpRight size={15}/></Link></div></div></article>;
}
function ProjectCard({ project, actorId }: { project: FreelanceProject; actorId?: string }) {
  const Icon = services[Math.max(0, freelanceSpecialties.indexOf(project.specialty))].icon;
  const href = '/thue-thiet-ke/' + project.id;
  const owner = actorId === project.ownerId;
  return <article className="fm-project-card"><div className="fm-project-top"><span className="fm-project-category"><Icon size={15}/>{project.specialty}</span><FreelanceBadge status={project.status}/></div><h3><Link href={href}>{project.title}</Link></h3><p className="fm-project-description">{project.description || 'Trao đổi để làm rõ nhu cầu, phạm vi và hồ sơ cần bàn giao.'}</p><div className="fm-project-meta"><span><MemberAvatar name={project.ownerName} className="size-5 text-[10px]"/>{project.ownerName}</span><span><MapPin size={14}/>{project.location || 'Làm việc trực tuyến'}</span>{project.days > 0 && <span>{project.days} ngày dự kiến</span>}</div><div className="fm-project-bottom"><div><small>Ngân sách dự kiến</small><b>{project.budget ? freelanceMoney(project.budget) : 'Thỏa thuận theo nhu cầu'}</b></div><span className="fm-project-quotes"><MessageSquare size={15}/>{project.proposalCount} đề xuất</span><Link className="fm-project-cta" href={href}>Xem dự án <ArrowUpRight size={16}/></Link></div><div className="fm-project-actions">{owner ? <Link className="fm-button fm-button-small" href={href + '?action=proposals'}>Xem báo giá nhận được<ArrowRight size={15}/></Link> : project.status === 'open' ? <><Link className="fm-button fm-button-small" href={href + '?action=proposal'}>Báo giá / nhận việc<ArrowUpRight size={15}/></Link><Link className="fm-button fm-button-small fm-button-outline" href={href + '?action=contact'}><MessageSquare size={15}/>Liên hệ người thuê</Link></> : null}</div></article>;
}
