"use client";
import { useEffect, useState } from "react";
import { PasswordChange } from "@/components/password-change";
import { AdminTotpSettings } from "@/components/admin-totp-settings";
import { Check, ChevronLeft, ChevronRight, Eye, EyeOff, FileText, LoaderCircle, Mail, Search, Settings2, Trash2, Undo2, Users, WalletCards } from "lucide-react";
import { OwnerFinance } from "@/components/owner-finance";
import { AdminEmpty, AdminError, AdminLoading, ReloadButton, StatusBadge } from "@/components/admin-ui";
import { adminDate, requestStatuses, type AdminMember, type AdminPost, type AdminRequest } from "@/lib/admin-types";
import type { ContentValue } from "@/lib/site-content";

const tabs = [{ id: "noi-dung", label: "Nội dung", Icon: FileText }, { id: "yeu-cau", label: "Yêu cầu", Icon: Mail }, { id: "thanh-vien", label: "Thành viên", Icon: Users }, { id: "giao-dich", label: "Giao dịch", Icon: WalletCards }, { id: "cai-dat", label: "Cài đặt", Icon: Settings2 }];
export function OwnerManagement({ tab, onTabChange, selectedPost, onEditSiteSetting }: { tab: string; onTabChange: (tab: string) => void; selectedPost?: number; onEditSiteSetting: (key: string, kind: ContentValue["kind"], fallback: string, label: string) => void }) {
  return <div className="owner-management"><nav className="owner-management-tabs" aria-label="Quản lý website">{tabs.map(({ id, label, Icon }) => <button type="button" key={id} onClick={() => onTabChange(id)} className={tab === id ? "active" : ""} aria-pressed={tab === id}><Icon size={16}/>{label}</button>)}</nav><div className="owner-management-content">{tab === "giao-dich" ? <OwnerFinance/> : tab === "cai-dat" ? <OwnerSettings onEdit={onEditSiteSetting}/> : <OwnerRecords key={tab} resource={tab === "yeu-cau" ? "requests" : tab === "thanh-vien" ? "members" : "posts"} selectedPost={selectedPost}/>}</div></div>;
}
type RecordItem = AdminPost | AdminRequest | AdminMember;
function OwnerRecords({ resource, selectedPost }: { resource: "posts" | "requests" | "members"; selectedPost?: number }) {
  const [items, setItems] = useState<RecordItem[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("");
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [revision, setRevision] = useState(0);
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [detail, setDetail] = useState<AdminPost | AdminRequest | null>(null);
  useEffect(() => {
    const controller = new AbortController();
    const timer = setTimeout(() => {
      setLoading(true); setError("");
      const params = new URLSearchParams({ page: String(page), q: query, filter });
      if (selectedPost && resource === "posts") params.set("id", String(selectedPost));
      fetch(`/api/admin/manage/${resource}?${params}`, { cache: "no-store", signal: controller.signal }).then(async response => { const data = await response.json() as { items: RecordItem[]; total: number; error?: string }; if (!response.ok) throw new Error(data.error || "Chưa thể tải nội dung."); return data; }).then(data => { setItems(data.items); setTotal(data.total); if (selectedPost) setDetail(data.items.find(item => "id" in item && item.id === selectedPost) as AdminPost || null); }).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Chưa thể tải dữ liệu."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    }, 0);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [resource, page, query, filter, revision, selectedPost]);
  async function update(body: Record<string, unknown>, method = "PATCH") {
    if (busy) return;
    setBusy(true); setError(""); setNotice("");
    try {
      const response = await fetch(`/api/admin/manage/${resource}`, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error || "Chưa thể cập nhật.");
      setDetail(null);
      if (method === "DELETE") setNotice("Đã chuyển bài đăng vào thùng rác. Bạn có thể khôi phục tại bộ lọc Thùng rác.");
      if (body.action === "restore") setNotice("Đã khôi phục bài đăng ở trạng thái ẩn. Chọn Đã ẩn rồi bấm Hiện để đăng lại.");
      if ((method === "DELETE" || body.action === "restore") && items.length === 1 && page > 1) setPage(value => value - 1);
      setRevision(value => value + 1); window.dispatchEvent(new Event("tipook-content-changed"));
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Chưa thể cập nhật."); } finally { setBusy(false); }
  }
  function deletePost(post: AdminPost) {
    if (busy || !window.confirm(`Chuyển bài đăng “${post.title}” vào thùng rác? Bài sẽ được gỡ khỏi website và có thể khôi phục lại.`)) return;
    void update({ id: post.id }, "DELETE");
  }
  const options = resource === "posts" ? [["public", "Đang hiển thị"], ["hidden", "Đã ẩn"], ["deleted", "Thùng rác"]] : resource === "requests" ? Object.entries(requestStatuses) : [["user", "Thành viên"], ["architect", "Kiến trúc sư"], ["engineer", "Kỹ sư"]];
  return <><div className="owner-records-intro"><div><h2>{resource === "posts" ? "Nội dung trên website" : resource === "requests" ? "Yêu cầu gửi tới bạn" : "Thành viên website"}</h2><p>{resource === "posts" ? "Sửa, ẩn hoặc xóa bài đăng. Bài đã xóa có thể khôi phục từ Thùng rác." : resource === "requests" ? "Xem thông tin liên hệ và cập nhật tiến độ xử lý." : "Tra cứu thông tin, loại tài khoản và hồ sơ thành viên."}</p></div><ReloadButton loading={loading} onClick={() => setRevision(value => value + 1)}/></div><AdminError error={error}/>{notice && <p className="admin-alert" role="status">{notice}</p>}
    {detail && (!("title" in detail) || detail.audience !== "Đã xóa bởi quản trị") && <section className="owner-record-detail"><h3>{"title" in detail ? "Chỉnh sửa bài đăng" : detail.subject}</h3>{"title" in detail ? <form className="owner-edit-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void update({ id: detail.id, title: form.get("title"), content: form.get("content") }); }}><label>Tiêu đề<input name="title" defaultValue={detail.title} required maxLength={120} disabled={busy}/></label><label>Nội dung<textarea name="content" defaultValue={detail.content} rows={5} maxLength={1200} disabled={busy}/></label><div className="owner-edit-actions"><button type="button" className="owner-secondary" onClick={() => setDetail(null)} disabled={busy}>Đóng</button><button type="button" className="admin-row-button danger" onClick={() => deletePost(detail)} disabled={busy}><Trash2 size={15}/>Xóa bài đăng</button><button className="owner-primary" disabled={busy}>{busy ? <LoaderCircle size={16} className="animate-spin"/> : <Check size={16}/>}Lưu bài đăng</button></div></form> : <><p className="admin-detail-content">{detail.content}</p><p className="mt-3 text-sm">Người gửi: {detail.authorName}</p><p className="mt-2 text-sm">Liên hệ: {detail.contact || "Chưa cung cấp"}</p><div className="owner-edit-actions"><button className="owner-secondary" type="button" onClick={() => setDetail(null)}>Đóng</button><select className="admin-select" aria-label="Cập nhật trạng thái yêu cầu" value={detail.status} onChange={event => void update({ id: detail.id, status: event.target.value })} disabled={busy}>{Object.entries(requestStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></>}</section>}
    <section className="admin-panel"><div className="admin-toolbar"><form className="admin-search" onSubmit={event => { event.preventDefault(); setPage(1); setQuery(search); }}><Search size={16}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm theo tên, tiêu đề hoặc email" aria-label="Tìm nội dung"/><button type="submit" aria-label="Tìm kiếm"><ChevronRight size={16}/></button></form><select className="admin-select" aria-label="Lọc danh sách" value={filter} onChange={event => { setFilter(event.target.value); setPage(1); }}><option value="">{resource === "posts" ? "Tất cả (trừ thùng rác)" : "Tất cả"}</option>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>
      {loading ? <AdminLoading/> : !items.length ? <AdminEmpty title={query || filter ? "Không có kết quả phù hợp" : "Chưa có nội dung"} description="Nội dung mới sẽ xuất hiện tại đây."/> : <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>{resource === "members" ? "Thành viên" : "Nội dung"}</th><th>{resource === "members" ? "Loại tài khoản" : "Người gửi"}</th><th>Thời gian</th><th>{resource === "members" ? "Bài đăng" : "Trạng thái"}</th>{resource !== "members" && <th>Thao tác</th>}</tr></thead><tbody>{items.map(item => "userId" in item ? <tr key={item.userId}><td><a href={`/nguoi-dung/${encodeURIComponent(item.userId)}`} className="admin-table-title">{item.displayName}</a><small>{item.email || "Chưa có email"}</small></td><td>{item.accountType === "architect" ? "Kiến trúc sư" : item.accountType === "engineer" ? "Kỹ sư" : "Thành viên"}</td><td className="admin-muted">{adminDate(item.updatedAt)}</td><td>{item.postCount}</td></tr> : <tr key={item.id}><td><button type="button" className="admin-table-title" disabled={"title" in item && item.audience === "Đã xóa bởi quản trị"} onClick={() => setDetail(item)}>{"title" in item ? item.title : item.subject}</button><small>{"title" in item ? item.category : `#${item.id}`}</small></td><td>{item.authorName}</td><td className="admin-muted">{adminDate(item.createdAt)}</td><td>{"title" in item ? <StatusBadge status={item.audience === "Công khai" ? "public" : item.audience === "Đã xóa bởi quản trị" ? "deleted" : "hidden"} label={item.audience === "Công khai" ? "Hiển thị" : item.audience === "Đã xóa bởi quản trị" ? "Thùng rác" : "Đã ẩn"}/> : <StatusBadge status={item.status} label={requestStatuses[item.status as keyof typeof requestStatuses] || item.status}/>}</td><td><div className="admin-row-actions">{"title" in item && item.audience === "Đã xóa bởi quản trị" ? <button type="button" className="admin-row-button" disabled={busy} onClick={() => void update({ id: item.id, action: "restore" })}><Undo2 size={15}/>Khôi phục</button> : <><button type="button" className="admin-row-button" disabled={busy} onClick={() => setDetail(item)}>Mở</button>{"title" in item && <button type="button" disabled={busy} className="admin-row-button" onClick={() => void update({ id: item.id, audience: item.audience === "Công khai" ? "Ẩn bởi quản trị" : "Công khai" })} aria-label={item.audience === "Công khai" ? "Ẩn bài đăng" : "Hiện bài đăng"}>{item.audience === "Công khai" ? <EyeOff size={15}/> : <Eye size={15}/>}</button>}{"title" in item && <button type="button" className="admin-row-button danger" disabled={busy} onClick={() => deletePost(item)} aria-label={`Xóa bài đăng ${item.title}`}><Trash2 size={15}/>Xóa</button>}</>}</div></td></tr>)}</tbody></table></div>}
      <div className="admin-pagination"><span>{total} mục · Trang {page}/{Math.max(1, Math.ceil(total / 20))}</span><div className="admin-pagination-controls"><button type="button" className="admin-row-button" disabled={page <= 1 || loading} onClick={() => setPage(value => value - 1)} aria-label="Trang trước"><ChevronLeft size={16}/></button><button type="button" className="admin-row-button" disabled={page * 20 >= total || loading} onClick={() => setPage(value => value + 1)} aria-label="Trang sau"><ChevronRight size={16}/></button></div></div>
    </section></>;
}
type SettingsData = { adminEmail?: string; bankCode?: string; bankAccount?: string; bankName?: string; database?: boolean; storage?: boolean; downloads?: boolean; passwordAccount?: boolean; authEmail?: boolean; adminTotp?: boolean };
function OwnerSettings({ onEdit }: { onEdit: (key: string, kind: ContentValue["kind"], fallback: string, label: string) => void }) {
  const [data, setData] = useState<SettingsData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); fetch("/api/admin/settings", { signal: controller.signal, cache: "no-store" }).then(async response => { const result = await response.json() as SettingsData & { error?: string }; if (!response.ok) throw new Error(result.error); return result; }).then(setData).catch(cause => { if (!controller.signal.aborted) setError(cause instanceof Error ? cause.message : "Chưa thể tải cấu hình."); }); return () => controller.abort(); }, []);
  return <><AdminError error={error}/><div className="owner-settings-grid"><section className="owner-settings-card"><h2>Diện mạo website</h2><p>Chỉnh sửa các thông tin chung và xem ngay trên giao diện.</p><div className="owner-setting-buttons"><button type="button" onClick={() => onEdit("global.name", "text", "Tipook", "Tên website")}>Tên website</button><button type="button" onClick={() => onEdit("global.logo", "image", "/tipook-logo.png", "Logo website")}>Thay logo</button><button type="button" onClick={() => onEdit("global.accent", "color", "#229ed9", "Màu chủ đạo")}>Màu chủ đạo</button></div><p className="owner-setting-help">Bạn có thể sửa tiêu đề, mô tả, bài hướng dẫn và ảnh mẫu ngay trên từng trang bằng nút “Chỉnh sửa”.</p></section>
    <section className="owner-settings-card"><h2>Tài khoản chủ website</h2><p>{data?.adminEmail || "Đang tải email chủ website..."}</p>{data?.passwordAccount && <><PasswordChange admin/><AdminTotpSettings/></>}</section>
    <section className="owner-settings-card"><h2>Kết nối dữ liệu</h2>{data ? <div className="owner-connection-list">{[["Cơ sở dữ liệu", data.database], ["Kho ảnh và tệp", data.storage], ["Liên kết tải bản vẽ", data.downloads], ["Xác thực quản trị TOTP", data.adminTotp], ["Email khôi phục thành viên", data.authEmail]].map(([label, ok]) => <div key={String(label)}><span>{label}</span><StatusBadge status={ok ? "completed" : "pending"} label={ok ? "Đã kết nối" : "Chưa cấu hình"}/></div>)}</div> : <AdminLoading/>}</section>
    <section className="owner-settings-card"><h2>Tài khoản nhận tiền</h2><div className="owner-connection-list"><div><span>Ngân hàng</span><strong>{data?.bankCode || "Chưa cấu hình"}</strong></div><div><span>Số tài khoản</span><strong>{data?.bankAccount || "Chưa cấu hình"}</strong></div><div><span>Chủ tài khoản</span><strong>{data?.bankName || "Chưa cấu hình"}</strong></div></div><p className="owner-setting-help">Thông tin nhận tiền và quyền chủ website được cấu hình trong biến môi trường của máy chủ.</p></section>
  </div></>;
}
