import { env } from 'cloudflare:workers';
import { getAuthenticatedIdentity, validOrigin } from '@/lib/website-auth';
import { freelanceSpecialties, type FreelanceActor, type FreelanceProfile, type FreelanceProject } from './freelance-types';

export class FreelanceError extends Error { constructor(message: string, public status = 400) { super(message); } }
export const freelanceHeaders = { 'Cache-Control': 'private, no-store' };
export function freelanceFailure(error: unknown) { return Response.json({ error: error instanceof FreelanceError ? error.message : 'Chưa thể xử lý yêu cầu. Vui lòng thử lại.' }, { status: error instanceof FreelanceError ? error.status : 500, headers: freelanceHeaders }); }
export async function freelanceActor(): Promise<FreelanceActor | null> { const identity = await getAuthenticatedIdentity(); return identity ? { id: identity.userId, name: identity.displayName } : null; }
export async function freelanceWriter(request: Request) { if (!validOrigin(request)) throw new FreelanceError('Nguồn yêu cầu không hợp lệ.', 403); const actor = await freelanceActor(); if (!actor) throw new FreelanceError('Vui lòng đăng nhập để tiếp tục.', 401); return actor; }
export async function freelanceBody(request: Request): Promise<Record<string, unknown>> { try { const body = await request.json(); if (!body || typeof body !== 'object' || Array.isArray(body)) throw new Error(); return body as Record<string, unknown>; } catch { throw new FreelanceError('Dữ liệu gửi lên không hợp lệ.'); } }
export function freelanceText(value: unknown, label: string, max: number, optional = false) { if (value == null && optional) return ''; if (typeof value !== 'string') throw new FreelanceError('Vui lòng nhập ' + label + '.'); const text = value.trim(); if ((!text && !optional) || text.length > max) throw new FreelanceError(`${label}: ${optional ? 'tối đa' : 'nhập từ 1 đến'} ${max} ký tự.`); return text; }
export function freelanceNumber(value: unknown, label: string, min: number, max: number) { if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < min || value > max) throw new FreelanceError(`${label}: nhập số nguyên từ ${min.toLocaleString('vi-VN')} đến ${max.toLocaleString('vi-VN')}.`); return value; }
export function freelanceSpecialty(value: unknown) { if (!(freelanceSpecialties as readonly unknown[]).includes(value)) throw new FreelanceError('Vui lòng chọn chuyên môn hợp lệ.'); return value as FreelanceProfile['specialty']; }
export function freelanceId(value: unknown) { if (typeof value !== 'string' || !/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(value)) throw new FreelanceError('Mã yêu cầu không hợp lệ.'); return value.toLowerCase(); }
export function freelanceUrl(value: unknown, optional = true) { const text = freelanceText(value, 'Liên kết', 1200, optional); if (!text) return ''; try { const url = new URL(text); if (url.protocol !== 'https:' || url.username || url.password) throw new Error(); return url.href; } catch { throw new FreelanceError('Liên kết phải bắt đầu bằng https://.'); } }
export const profileColumns = `f.user_id AS id,f.display_name AS name,f.title,f.specialty,f.location,f.bio,f.skills,f.experience,f.rate,f.rate_unit AS rateUnit,f.available,f.cover,f.portfolio,f.updated_at AS updatedAt,(SELECT COUNT(*) FROM freelance_projects p WHERE p.freelancer_id = f.user_id AND p.status = 'completed') AS completedCount`;
type ProfileRow = Omit<FreelanceProfile, 'skills' | 'portfolio' | 'available'> & { skills: string; portfolio: string; available: number };
export function parseFreelanceProfile(row: ProfileRow): FreelanceProfile { return { ...row, available: Boolean(row.available), skills: JSON.parse(row.skills), portfolio: JSON.parse(row.portfolio) }; }
export async function getFreelanceProfile(id: string) { const row = await env.DB!.prepare(`SELECT ${profileColumns} FROM freelance_profiles f LEFT JOIN member_profiles m ON m.user_id = f.user_id WHERE f.user_id = ? AND COALESCE(m.account_status,'active') = 'active'`).bind(id).first<ProfileRow>(); return row ? parseFreelanceProfile(row) : null; }
export const projectColumns = `p.id,p.owner_id AS ownerId,p.owner_name AS ownerName,p.freelancer_id AS freelancerId,p.title,p.specialty,p.description,p.location,p.budget,p.days,p.status,p.agreed_price AS agreedPrice,p.agreed_days AS agreedDays,p.created_at AS createdAt,p.updated_at AS updatedAt,(SELECT COUNT(*) FROM freelance_proposals r WHERE r.project_id = p.id) AS proposalCount`;
export async function getFreelanceProject(id: string) { const project = await env.DB!.prepare(`SELECT ${projectColumns} FROM freelance_projects p WHERE p.id = ?`).bind(id).first<FreelanceProject>(); if (!project) throw new FreelanceError('Dự án không tồn tại trên nền tảng mới.', 404); return project; }
export function projectParticipant(project: FreelanceProject, actor: FreelanceActor | null) { return Boolean(actor && (actor.id === project.ownerId || actor.id === project.freelancerId)); }
export type { ProfileRow };
