import assert from 'node:assert/strict';
import { canonicalUrl, pageMetadata, postStructuredData, serializeStructuredData, seoCatalogPage } from '../lib/seo.ts';
import { robotsResponse } from '../lib/seo-robots.ts';
assert.equal(canonicalUrl('/bai-viet/12?return_to=x#post-12'), 'https://nhadepchat.top/bai-viet/12');
assert.equal(canonicalUrl('/noi-that?page=2&q=abc'), 'https://nhadepchat.top/noi-that?page=2');
assert.equal(canonicalUrl('/noi-that?page=0'), 'https://nhadepchat.top/noi-that');
assert.throws(() => canonicalUrl('//foreign.example/post'));
assert.throws(() => canonicalUrl('https://foreign.example/post'));
assert.equal(seoCatalogPage(['2','3']), 1);
assert.equal(seoCatalogPage('1000001'), 1);
assert.equal(seoCatalogPage('2'), 2);
const text = '</script><script>alert(1)</script>&\u2028';
const schema = postStructuredData({ id: 12, userId: 'member_12', title: text, content: 'Visible text', createdAt: '2026-10-04T00:00:00Z', authorName: 'Member', images: [{ url: '/api/files?key=public&x=1' }], comments: 3 });
const serialized = serializeStructuredData(schema);
assert.ok(!serialized.includes('</script>'));
assert.ok(!serialized.includes('<'));
assert.deepEqual(JSON.parse(serialized), schema);
assert.equal(schema['@type'], 'SocialMediaPosting');
assert.equal(schema.headline, text);
assert.equal(schema.commentCount, 3);
assert.equal(schema.author.url, 'https://nhadepchat.top/nguoi-dung/member_12');
assert.equal(schema.dateModified, undefined, 'Do not fabricate modification dates');
assert.equal(schema.comment, undefined, 'Do not mark up comments that are not initially visible');
const metadata = pageMetadata('Post title', 'Line one\nLine two', '/bai-viet/12');
assert.equal(metadata.alternates.canonical, 'https://nhadepchat.top/bai-viet/12');
assert.equal(metadata.description, 'Line one Line two');
const robots = robotsResponse();
assert.equal(robots.headers.get('content-type'), 'text/plain; charset=utf-8');
const directives = await robots.text();
assert.ok(directives.includes('Sitemap: https://nhadepchat.top/sitemap.xml'));
assert.ok(!directives.includes('Disallow: /api/files'));
assert.ok(!directives.includes('Disallow: /_next/'));
assert.equal(robotsResponse('HEAD').body, null);
console.log('PASS: canonical safety, pagination normalization, metadata, structured data, script escaping and robots discovery.');
