"use client";
import {useMemo,useState} from "react";
import {Calculator,ChevronRight,Copy,FileDown,FolderOpen,Plus,Save,Trash2} from "lucide-react";

type ItemId="rebar"|"blinding"|"footing"|"pedestal"|"gradeBeam"|"column"|"beam"|"slab"|"stair"|"floorBase"|"masonry"|"plaster"|"floorTile"|"wallTile"|"paint";
type Result={label:string;value:string;note?:string};
type FootingType="isolated"|"combined"|"stepped"|"strip"|"raft"|"pile";
const footingTypes:readonly (readonly [FootingType,string])[]=[
 ["isolated","Móng đơn vát"],["combined","Móng liên hợp bản phẳng (2 cột)"],["stepped","Móng đơn giật cấp"],["strip","Móng băng tiết diện vát"],["raft","Móng bè bản phẳng"],["pile","Đài cọc + cọc tròn BTCT"]
];
const groups=[
 {title:"Kết cấu bê tông",items:[["blinding","Bê tông lót"],["footing","Bê tông móng"],["pedestal","Bê tông cổ cột"],["gradeBeam","Bê tông đà kiềng"],["column","Bê tông cột"],["beam","Bê tông dầm"],["slab","Bê tông sàn"],["stair","Bê tông cầu thang"]]},
 {title:"Xây và lớp nền",items:[["floorBase","Ba ta nền"],["masonry","Gạch xây tường"],["plaster","Trát tường"]]},
 {title:"Hoàn thiện",items:[["floorTile","Gạch lát nền"],["wallTile","Gạch ốp tường"],["paint","Sơn nước"]]},
] as const;
const names=Object.fromEntries(groups.flatMap(g=>g.items)) as Record<ItemId,string>;
const defaults:Record<string,string>={qty:"1",waste:"3",length:"5",width:".2",height:".3",thickness:".1",openings:"0",bottomA:"2",bottomB:"2",topA:"1",topB:"1",totalH:".8",baseH:".25",rise:".17",tread:".25",steps:"18",stairWidth:"1",waist:".12",upperH:".4",pileDiameter:".3",pileLength:"6",pileCount:"4",sides:"2",tileW:".6",tileH:".6",coverage:"10",coats:"2"};
const mixes={M100:{cement:218,sand:.516,stone:.831,water:185},M150:{cement:250,sand:.505,stone:.824,water:190},M200:{cement:277,sand:.503,stone:.82,water:198},M250:{cement:323,sand:.492,stone:.803,water:198},M300:{cement:366,sand:.482,stone:.787,water:198}};
const fmt=(v:number,d=3)=>new Intl.NumberFormat("vi-VN",{maximumFractionDigits:d}).format(v);
const n=(v:string)=>{const x=Number((v||"").replace(",","."));return Number.isFinite(x)&&x>0?x:0};
const concreteIds=new Set<ItemId>(["blinding","footing","pedestal","gradeBeam","column","beam","slab","stair"]);

function Field({label,k,v,set,unit="m",step="0.01"}:{label:string;k:string;v:Record<string,string>;set:(k:string,x:string)=>void;unit?:string;step?:string}){
 return <label><span className="mb-1 block text-xs font-bold text-[#344054]">{label}</span><span className="flex h-9 overflow-hidden rounded-xl border border-[#dce5ef] bg-white focus-within:border-[#229ed9] focus-within:ring-4 focus-within:ring-[#229ed9]/10"><input type="number" min="0" step={step} value={v[k]} onChange={e=>set(k,e.target.value)} className="min-w-0 flex-1 px-3 text-sm font-semibold outline-none"/><span className="grid min-w-12 place-items-center border-l bg-[#f7f9fb] px-2 text-xs font-bold text-[#667085]">{unit}</span></span></label>
}
function FootingPreview({type}:{type:FootingType}){
 type P3=readonly [number,number,number];
 const project=([x,y,z]:P3):[number,number]=>[260+(x-y)*48,225+(x+y)*22-z*76];
 const points=(items:P3[])=>items.map(point=>project(point).join(",")).join(" ");
 const corners=(width:number,depth:number,z:number):P3[]=>[[-width/2,-depth/2,z],[width/2,-depth/2,z],[width/2,depth/2,z],[-width/2,depth/2,z]];
 const solid=(bottomWidth:number,bottomDepth:number,topWidth:number,topDepth:number,z0:number,z1:number)=>{const lower=corners(bottomWidth,bottomDepth,z0),upper=corners(topWidth,topDepth,z1);return <g stroke="#0b4f88" strokeWidth="1.8" strokeLinejoin="round"><polygon points={points([lower[0],lower[1],upper[1],upper[0]])} fill="#d8eff9"/><polygon points={points([lower[1],lower[2],upper[2],upper[1]])} fill="#acdcef"/><polygon points={points([lower[2],lower[3],upper[3],upper[2]])} fill="#91cde5"/><polygon points={points([lower[3],lower[0],upper[0],upper[3]])} fill="#c6e8f5"/><polygon points={points(upper)} fill="#eaf8fd"/></g>};
 const dim=(a:P3,b:P3,label:string,dx=0,dy=0)=>{const p1=project(a),p2=project(b),mx=(p1[0]+p2[0])/2+dx,my=(p1[1]+p2[1])/2+dy;return <g><line x1={p1[0]} y1={p1[1]} x2={p2[0]} y2={p2[1]} stroke="#168ac0" strokeWidth="1.4" markerStart="url(#dim-arrow)" markerEnd="url(#dim-arrow)"/><rect x={mx-13} y={my-10} width="26" height="18" rx="6" fill="white" opacity=".94"/><text x={mx} y={my+3} textAnchor="middle" fill="#0879ad" fontSize="12" fontWeight="800">{label}</text></g>};
 const captions:Record<FootingType,string>={
  isolated:"A, B: kích thước đáy · a, b: kích thước mặt trên · H: tổng chiều cao · h: chiều dày bản đế móng BTCT (không phải lớp lót)",
  combined:"L, B: kích thước bản móng liên hợp · H: chiều dày bản · hai ô nét đứt: vị trí cột/cổ cột, không cộng thể tích",
  stepped:"A, B: bậc dưới · a, b: bậc trên · h₁, h₂: chiều cao từng bậc",
  strip:"L: tổng chiều dài · B: rộng đáy · b: rộng mặt trên · H: tổng cao · h: dày bản đế móng băng BTCT (không phải lớp lót)",
  raft:"L, W: kích thước mặt bằng · t: chiều dày bản móng bè",
  pile:"A, B, H: kích thước đài · d: đường kính cọc · Lc: chiều dài cọc"
 };
 let geometry:React.ReactNode;
 if(type==="raft")geometry=<>{solid(4.4,2.7,4.4,2.7,0,.34)}{dim([-2.2,1.62,0],[2.2,1.62,0],"L",0,18)}{dim([2.55,-1.35,0],[2.55,1.35,0],"W",18,0)}{dim([-2.45,-1.35,0],[-2.45,-1.35,.34],"t",-18,0)}</>;
 else if(type==="pile"){
  const pilePoints:P3[]=[[-1.35,-.72,0],[1.35,-.72,0],[-1.35,.72,0],[1.35,.72,0]];
  geometry=<><g>{pilePoints.map((point,index)=>{const top: P3=[point[0],point[1],1.68],p0=project(point),p1=project(top);return <g key={index}><line x1={p0[0]} y1={p0[1]} x2={p1[0]} y2={p1[1]} stroke="#397796" strokeWidth="11" strokeLinecap="round"/><ellipse cx={p0[0]} cy={p0[1]} rx="6" ry="3" fill="#0b4f88"/></g>})}</g>{solid(3.4,2.15,3.4,2.15,1.45,2.12)}{dim([-1.7,1.36,1.45],[1.7,1.36,1.45],"A",0,17)}{dim([2.02,-1.075,1.45],[2.02,1.075,1.45],"B",18,0)}{dim([-2,-1.075,1.45],[-2,-1.075,2.12],"H",-18,0)}{dim([1.75,-1.075,0],[1.75,-1.075,1.45],"Lc",20,0)}{dim([-1.51,-.72,0],[-1.19,-.72,0],"d",0,17)}</>;
 }
 else if(type==="stepped")geometry=<>{solid(3.9,2.55,3.9,2.55,0,.38)}{solid(2.25,1.38,2.25,1.38,.38,1.05)}{dim([-1.95,1.55,0],[1.95,1.55,0],"A",0,18)}{dim([2.3,-1.275,0],[2.3,1.275,0],"B",18,0)}{dim([-1.125,-1.08,1.05],[1.125,-1.08,1.05],"a",0,-16)}{dim([1.5,-.69,1.05],[1.5,.69,1.05],"b",18,0)}{dim([-2.2,-1.275,0],[-2.2,-1.275,.38],"h₁",-19,0)}{dim([-1.45,-.69,.38],[-1.45,-.69,1.05],"h₂",-19,0)}</>;
 else if(type==="combined"){
  const left=corners(.62,.62,.5).map(([x,y,z])=>[x-1.15,y,z] as P3),right=corners(.62,.62,.5).map(([x,y,z])=>[x+1.15,y,z] as P3);
  geometry=<>{solid(4.5,2.4,4.5,2.4,0,.5)}<polygon points={points(left)} fill="none" stroke="#d92d20" strokeWidth="2" strokeDasharray="6 4"/><polygon points={points(right)} fill="none" stroke="#d92d20" strokeWidth="2" strokeDasharray="6 4"/>{dim([-2.25,1.58,0],[2.25,1.58,0],"L",0,18)}{dim([2.62,-1.2,0],[2.62,1.2,0],"B",18,0)}{dim([-2.55,-1.2,0],[-2.55,-1.2,.5],"H",-18,0)}<text x="260" y="73" textAnchor="middle" fill="#d92d20" fontSize="10" fontWeight="700">VỊ TRÍ 2 CỘT / CỔ CỘT</text></>;
 }
 else if(type==="strip")geometry=<>{solid(4.7,1.75,4.7,1.75,0,.3)}{solid(4.7,1.75,4.7,.72,.3,1.05)}{dim([-2.35,1.22,0],[2.35,1.22,0],"L",0,18)}{dim([2.72,-.875,0],[2.72,.875,0],"B",18,0)}{dim([2.72,-.36,1.05],[2.72,.36,1.05],"b",18,0)}{dim([-2.65,-.875,0],[-2.65,-.875,1.05],"H",-18,0)}{dim([-2.65,.875,0],[-2.65,.875,.3],"h",-18,0)}</>;
 else {
  const width=type==="combined"?4.4:3.6,topWidth=type==="combined"?2.8:1.75;
  geometry=<>{solid(width,2.55,width,2.55,0,.3)}{solid(width,2.55,topWidth,1.15,.3,1.2)}{dim([-width/2,1.62,0],[width/2,1.62,0],"A",0,18)}{dim([width/2+.38,-1.275,0],[width/2+.38,1.275,0],"B",18,0)}{dim([-topWidth/2,-.9,1.2],[topWidth/2,-.9,1.2],"a",0,-16)}{dim([topWidth/2+.35,-.575,1.2],[topWidth/2+.35,.575,1.2],"b",18,0)}{dim([-width/2-.35,-1.275,0],[-width/2-.35,-1.275,1.2],"H",-18,0)}{dim([-width/2-.35,1.275,0],[-width/2-.35,1.275,.3],"h",-18,0)}</>;
 }
 return <figure className="mt-3 overflow-hidden rounded-xl border border-[#dce5ef] bg-white"><div className="flex items-center justify-between border-b bg-[#f8fafc] px-3 py-2"><b className="text-xs text-[#344054]">Hình mô phỏng không gian</b><span className="text-[11px] text-[#667085]">Hình quy ước · Không theo tỷ lệ</span></div><svg viewBox="0 0 520 300" role="img" aria-label={`Hình mô phỏng ${footingTypes.find(([id])=>id===type)?.[1]}`} className="mx-auto block h-auto w-full max-w-[540px] p-2"><defs><marker id="dim-arrow" markerWidth="7" markerHeight="7" refX="3.5" refY="3.5" orient="auto-start-reverse"><path d="M0,0 L7,3.5 L0,7 Z" fill="#168ac0"/></marker></defs>{geometry}</svg><figcaption className="border-t px-3 py-2 text-[11px] leading-5 text-[#52677f]">{captions[type]}</figcaption></figure>;
}
type BarShape="straight"|"hook"|"doubleHook"|"l"|"lHook"|"u"|"uHook"|"z"|"zHook"|"crank"|"doubleCrank"|"stirrup"|"stirrup135"|"openStirrup"|"cShape"|"sShape"|"chair"|"diamond"|"circle"|"spiral"|"custom"|"custom4"|"custom5";
type RebarBar={id:number;mark:string;diameter:string;shape:BarShape;a:string;b:string;c:string;d:string;e:string;qty:string;laps:string;lapFactor:string};
type RebarMember={id:number;name:string;qty:string;bars:RebarBar[]};
type RebarSheet={id:number;name:string;members:RebarMember[]};
const shapeNames:Record<BarShape,string>={straight:"Thanh thẳng",hook:"Móc một đầu",doubleHook:"Móc hai đầu",l:"Chữ L",lHook:"L có móc",u:"Chữ U",uHook:"U có móc",z:"Chữ Z",zHook:"Z có móc",crank:"Vai bò đơn",doubleCrank:"Vai bò đôi",stirrup:"Đai kín",stirrup135:"Đai móc 135°",openStirrup:"Đai hở",cShape:"Chữ C",sShape:"Chữ S",chair:"Thép ghế",diamond:"Đai thoi",circle:"Đai tròn",spiral:"Thép xoắn",custom:"Tổ hợp 3 đoạn",custom4:"Tổ hợp 4 đoạn",custom5:"Tổ hợp 5 đoạn"};
const shapeOrder=Object.keys(shapeNames) as BarShape[];
type DimensionKey="a"|"b"|"c"|"d"|"e";
const shapeFields:Record<BarShape,readonly DimensionKey[]>={straight:["a"],hook:["a","b"],doubleHook:["a","b"],l:["a","b"],lHook:["a","b","c"],u:["a","b"],uHook:["a","b","c"],z:["a","b","c"],zHook:["a","b","c","d"],crank:["a","b","c"],doubleCrank:["a","b","c","d"],stirrup:["a","b","c"],stirrup135:["a","b","c"],openStirrup:["a","b","c"],cShape:["a","b"],sShape:["a","b","c"],chair:["a","b","c"],diamond:["a","b","c"],circle:["a","b"],spiral:["a","b","c"],custom:["a","b","c"],custom4:["a","b","c","d"],custom5:["a","b","c","d","e"]};
const dimensionDefaults:Record<DimensionKey,string>={a:"1000",b:"200",c:"100",d:"100",e:"100"};
const blankBar=(id=1):RebarBar=>({id,mark:String(id),diameter:"16",shape:"straight",a:"1000",b:"0",c:"0",d:"0",e:"0",qty:"1",laps:"0",lapFactor:"30"});
const normalizeBar=(bar:Partial<RebarBar>,id=1):RebarBar=>{const merged={...blankBar(id),...bar,id:bar.id??id};for(const key of ["a","b","c","d","e"] as DimensionKey[]){const value=n(String(merged[key]??"0"));merged[key]=String(value>0&&value<50?value*1000:value)}return merged};
const barBaseLength=(bar:RebarBar)=>{const A=n(bar.a),B=n(bar.b),C=n(bar.c),D=n(bar.d),E=n(bar.e);let millimeters:number;switch(bar.shape){case "hook":case "l":millimeters=A+B;break;case "doubleHook":millimeters=A+2*B;break;case "lHook":case "z":case "custom":millimeters=A+B+C;break;case "u":case "cShape":millimeters=A+2*B;break;case "uHook":case "stirrup135":millimeters=A+2*B+2*C;break;case "zHook":case "custom4":millimeters=A+B+C+D;break;case "crank":case "sShape":millimeters=A+2*B+C;break;case "doubleCrank":millimeters=A+2*B+2*C+D;break;case "stirrup":case "diamond":millimeters=2*(A+B)+C;break;case "openStirrup":case "chair":millimeters=A+2*B+2*C;break;case "circle":millimeters=Math.PI*A+B;break;case "spiral":millimeters=Math.hypot(Math.PI*A,B)*C;break;case "custom5":millimeters=A+B+C+D+E;break;default:millimeters=A}return millimeters/1000};
const barCalc=(bar:RebarBar,memberQty:number)=>{const d=n(bar.diameter),lengthOne=barBaseLength(bar)+n(bar.laps)*n(bar.lapFactor)*d/1000,bars=n(bar.qty)*memberQty,totalLength=lengthOne*bars,weight=totalLength*d*d/162;return {lengthOne,bars,totalLength,weight}};
const dimensionLabel=(shape:BarShape,key:DimensionKey)=>shape==="spiral"?({a:"Đường kính D (mm)",b:"Bước xoắn (mm)",c:"Số vòng",d:"D",e:"E"}[key]):shape==="circle"?({a:"Đường kính D (mm)",b:"Đoạn nối (mm)",c:"C",d:"D",e:"E"}[key]):`${key.toUpperCase()} (mm)`;
const barDimensions=(bar:RebarBar)=>bar.shape==="spiral"?`D=${fmt(n(bar.a),0)} · bước=${fmt(n(bar.b),0)} · ${fmt(n(bar.c),0)} vòng`:shapeFields[bar.shape].map(key=>`${key.toUpperCase()}=${fmt(n(bar[key]),0)}`).join(" · ");

const shapePaths:Record<BarShape,string>={straight:"M8 28H92",hook:"M10 28H82Q93 28 90 16Q88 8 80 12",doubleHook:"M18 12Q8 8 10 20Q11 28 20 28H80Q89 28 90 20Q92 8 82 12",l:"M12 8V28H92",lHook:"M12 8V28H82Q92 28 90 17",u:"M14 8V28H86V8",uHook:"M14 8V28H86V8M14 8Q14 3 20 4M86 8Q86 3 80 4",z:"M10 8H42L58 28H92",zHook:"M10 8H40L58 28H82Q92 28 90 17",crank:"M8 28H34L48 10H66L78 28H94",doubleCrank:"M6 28H22L34 10H48L60 28H74L86 10H96",stirrup:"M20 7H80V33H20V7M20 7L29 15",stirrup135:"M22 6H78V33H22V6M22 6L34 17M78 33L66 22",openStirrup:"M17 7V32H83V7M17 7L28 16M83 7L72 16",cShape:"M82 8H18V32H82",sShape:"M12 9H54V20H88V32H48",chair:"M8 31H28L38 10H62L72 31H94",diamond:"M50 5L88 20L50 35L12 20L50 5M12 20L23 23",circle:"M50 5A32 15 0 1 1 49 5M49 5L58 12",spiral:"M8 28C15 8 25 8 32 28S49 48 56 28S73 8 80 28S91 44 96 22",custom:"M8 28H35L50 10L66 28H94",custom4:"M7 29H28L40 11H60L72 29H94",custom5:"M6 29H22L34 11H49L61 29H76L88 11H96"};
function ShapeSvg({shape,className="h-8 w-20"}:{shape:BarShape;className?:string}){
 return <svg viewBox="0 0 100 40" className={className} aria-hidden="true"><path d={shapePaths[shape]} fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
function DimensionedBar({bar}:{bar:RebarBar}){
 const positions:Record<DimensionKey,{x:number;y:number;x1:number;y1:number;x2:number;y2:number}>={a:{x:110,y:72,x1:34,y1:62,x2:186,y2:62},b:{x:17,y:40,x1:27,y1:16,x2:27,y2:56},c:{x:203,y:40,x1:193,y1:16,x2:193,y2:56},d:{x:68,y:10,x1:43,y1:15,x2:92,y2:15},e:{x:152,y:10,x1:128,y1:15,x2:177,y2:15}};
 return <svg viewBox="0 0 220 78" className="mx-auto h-[66px] w-full min-w-52 max-w-72 text-[#00e5ff]" role="img" aria-label={`${shapeNames[bar.shape]}, ${barDimensions(bar)}`}><g transform="translate(30 14) scale(1.6 1.05)"><path d={shapePaths[bar.shape]} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/></g>{shapeFields[bar.shape].map(key=>{const point=positions[key];return <g key={key} fill="currentColor" stroke="currentColor"><line x1={point.x1} y1={point.y1} x2={point.x2} y2={point.y2} strokeWidth=".7" opacity=".8"/><line x1={point.x1} y1={point.y1-3} x2={point.x1} y2={point.y1+3} strokeWidth=".7"/><line x1={point.x2} y1={point.y2-3} x2={point.x2} y2={point.y2+3} strokeWidth=".7"/><rect x={point.x-17} y={point.y-8} width="34" height="11" fill="#000"/><text x={point.x} y={point.y} textAnchor="middle" stroke="none" fontSize="9">{fmt(n(bar[key]),0)}</text></g>})}</svg>;
}

function RebarTakeoff(){
 const initialMember:RebarMember={id:1,name:"Cấu kiện 1",qty:"1",bars:[blankBar(1)]};
 const [sheets,setSheets]=useState<RebarSheet[]>([{id:1,name:"BTKT 1",members:[initialMember]}]),[sheetId,setSheetId]=useState(1),[memberId,setMemberId]=useState(1),[showAll,setShowAll]=useState(false),[groupByDiameter,setGroupByDiameter]=useState(true),[editingId,setEditingId]=useState<number|null>(null),[draft,setDraft]=useState<RebarBar>(blankBar(2)),[waste,setWaste]=useState("0");
 const sheet=sheets.find(item=>item.id===sheetId)??sheets[0],member=sheet.members.find(item=>item.id===memberId)??sheet.members[0];
 const changeSheet=(transform:(sheet:RebarSheet)=>RebarSheet)=>setSheets(current=>current.map(item=>item.id===sheet.id?transform(item):item));
 const changeMember=(transform:(member:RebarMember)=>RebarMember)=>changeSheet(current=>({...current,members:current.members.map(item=>item.id===member.id?transform(item):item)}));
 const editDraft=(key:keyof RebarBar,value:string)=>setDraft(current=>({...current,[key]:value}));
 const chooseShape=(shape:BarShape)=>setDraft(current=>{const next={...current,shape};for(const key of ["a","b","c","d","e"] as DimensionKey[])next[key]=shapeFields[shape].includes(key)?(shapeFields[current.shape].includes(key)&&n(current[key])>0?current[key]:dimensionDefaults[key]):"0";return next});
 const addSheet=()=>{const id=Date.now(),first:RebarMember={id:id+1,name:"Cấu kiện 1",qty:"1",bars:[]};setSheets(current=>[...current,{id,name:`BTKT ${current.length+1}`,members:[first]}]);setSheetId(id);setMemberId(first.id);setShowAll(false)};
 const addMember=(source?:RebarMember)=>{const id=Date.now(),created:RebarMember={id,name:source?`${source.name} copy`:`Cấu kiện ${sheet.members.length+1}`,qty:source?.qty??"1",bars:source?source.bars.map((bar,index)=>({...bar,id:id+index+1})):[]};changeSheet(current=>({...current,members:[...current.members,created]}));setMemberId(id);setShowAll(false)};
 const removeMember=()=>{if(sheet.members.length===1)return;const remaining=sheet.members.filter(item=>item.id!==member.id);changeSheet(current=>({...current,members:remaining}));setMemberId(remaining[0].id)};
 const selectBar=(bar:RebarBar)=>{setEditingId(bar.id);setDraft(normalizeBar(bar,bar.id))};
 const resetDraft=()=>{setEditingId(null);setDraft(blankBar(Math.max(0,...sheet.members.flatMap(item=>item.bars.map(bar=>bar.id)))+1))};
 const saveBar=()=>{changeMember(current=>({...current,bars:editingId===null?[...current.bars,{...draft}]:current.bars.map(bar=>bar.id===editingId?{...draft,id:editingId}:bar)}));resetDraft()};
 const removeBar=()=>{if(editingId===null)return;changeMember(current=>({...current,bars:current.bars.filter(bar=>bar.id!==editingId)}));resetDraft()};
 const duplicateBar=()=>{if(editingId===null)return;const id=Math.max(0,...sheet.members.flatMap(item=>item.bars.map(bar=>bar.id)))+1,copy={...draft,id,mark:String(id)};changeMember(current=>({...current,bars:[...current.bars,copy]}));setEditingId(id);setDraft(copy)};
 const moveBar=(direction:-1|1)=>{if(editingId===null)return;changeMember(current=>{const index=current.bars.findIndex(bar=>bar.id===editingId),target=index+direction;if(index<0||target<0||target>=current.bars.length)return current;const bars=[...current.bars];[bars[index],bars[target]]=[bars[target],bars[index]];return {...current,bars}})};
 const visibleMembers=useMemo(()=>showAll?sheet.members:[member],[showAll,sheet.members,member]);
 const summary=useMemo(()=>{const map=new Map<string,{length:number;weight:number}>();visibleMembers.forEach(part=>part.bars.forEach(bar=>{const result=barCalc(bar,n(part.qty)),d=n(bar.diameter),key=groupByDiameter?`Ø${d}`:d<=10?"Ø ≤ 10":d<=18?"10 < Ø ≤ 18":"Ø > 18",current=map.get(key)||{length:0,weight:0};current.length+=result.totalLength;current.weight+=result.weight;map.set(key,current)}));return [...map.entries()]},[visibleMembers,groupByDiameter]);
 const totalWeight=summary.reduce((sum,[,value])=>sum+value.weight,0)*(1+n(waste)/100);
 const exportXls=()=>{const rows=visibleMembers.flatMap(part=>part.bars.map(bar=>{const result=barCalc(bar,n(part.qty));return `<tr><td>${part.name}</td><td>${bar.mark}</td><td>Ø${bar.diameter}</td><td>${shapeNames[bar.shape]}</td><td>${result.bars}</td><td>${fmt(result.lengthOne)}</td><td>${fmt(result.totalLength)}</td><td>${fmt(result.weight)}</td></tr>`})).join("");const html=`<html><meta charset="utf-8"><table border="1"><tr><th>Cấu kiện</th><th>SH</th><th>ĐK</th><th>Hình dạng</th><th>Số thanh</th><th>L1 (m)</th><th>Tổng L (m)</th><th>Kg</th></tr>${rows}</table></html>`,blob=new Blob([html],{type:"application/vnd.ms-excel;charset=utf-8"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${sheet.name}.xls`;link.click();URL.revokeObjectURL(url)};
 const saveProject=()=>{const blob=new Blob([JSON.stringify(sheets,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="thong-ke-thep.tip.json";link.click();URL.revokeObjectURL(url)};
 const openProject=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(String(reader.result)) as RebarSheet[],data=raw.map(table=>({...table,members:table.members.map(part=>({...part,bars:part.bars.map((bar,index)=>normalizeBar(bar,bar.id??index+1))}))}));if(data.length&&data[0].members.length){setSheets(data);setSheetId(data[0].id);setMemberId(data[0].members[0].id);setEditingId(null);setDraft(blankBar())}}catch{window.alert("Tệp dữ liệu không hợp lệ")}};reader.readAsText(file)};
 const draftResult=barCalc(draft,n(member.qty));
 return <section className="overflow-hidden rounded-xl border border-[#aebdca] bg-[#dfe6ec] shadow-sm">
  <div className="flex flex-wrap items-center gap-1 border-b border-[#aebdca] bg-[#edf1f4] p-2 text-[#28445f]">
   <button type="button" onClick={addSheet} className="flex h-9 items-center gap-1.5 rounded border border-[#aab9c6] bg-white px-2.5 text-xs font-bold"><Plus size={15}/>Bảng mới</button>
   <button type="button" onClick={saveProject} className="flex h-9 items-center gap-1.5 rounded border border-[#aab9c6] bg-white px-2.5 text-xs font-bold"><Save size={15}/>Lưu</button>
   <label className="flex h-9 cursor-pointer items-center gap-1.5 rounded border border-[#aab9c6] bg-white px-2.5 text-xs font-bold"><FolderOpen size={15}/>Mở<input type="file" accept="application/json,.json" onChange={e=>openProject(e.target.files?.[0])} className="hidden"/></label>
   <button type="button" onClick={exportXls} className="flex h-9 items-center gap-1.5 rounded border border-[#aab9c6] bg-white px-2.5 text-xs font-bold"><FileDown size={15}/>Xuất XLS</button>
   <button type="button" onClick={()=>setShowAll(value=>!value)} className={`ml-auto h-9 rounded border px-3 text-xs font-bold ${showAll?"border-[#0879ad] bg-[#0879ad] text-white":"border-[#aab9c6] bg-white"}`}>{showAll?"Đang xem toàn bảng":"Xem từng cấu kiện"}</button>
  </div>

  <div className="bg-[#080d10] p-2 sm:p-4">
   <div className="mx-auto max-w-[1040px] overflow-hidden border border-[#d8df00] bg-black">
    <div className="border-b border-[#d8df00] px-3 py-2 text-center text-base font-bold uppercase tracking-wide text-[#00e5ff]">Bảng thống kê cốt thép</div>
    <div className="overflow-auto">
     <table className="w-full min-w-[820px] border-collapse text-[11px] text-white">
      <thead className="text-[#f2f500]"><tr className="divide-x divide-[#d8df00]"><th rowSpan={2} className="w-20 p-2">Tên<br/>cấu kiện</th><th rowSpan={2} className="w-14">Số<br/>hiệu</th><th rowSpan={2} className="min-w-72">Hình dạng - kích thước</th><th rowSpan={2} className="w-20">Đường kính<br/>(mm)</th><th rowSpan={2} className="w-24">Chiều dài<br/>1 thanh (mm)</th><th colSpan={2} className="border-b border-[#d8df00]">Số lượng</th><th rowSpan={2} className="w-24">Tổng chiều dài<br/>(m)</th><th rowSpan={2} className="w-24">Trọng lượng<br/>(kg)</th></tr><tr className="divide-x divide-[#d8df00] border-t border-[#d8df00]"><th className="w-16 py-1">Cấu kiện</th><th className="w-16">Toàn bộ</th></tr></thead>
      <tbody>{visibleMembers.flatMap(part=>part.bars.map((bar,index)=>{const result=barCalc(bar,n(part.qty));return <tr key={`${part.id}-${bar.id}`} onClick={()=>{if(!showAll)selectBar(bar)}} className={`cursor-pointer border-t border-[#d8df00] hover:bg-white/10 ${editingId===bar.id&&!showAll?"bg-[#00e5ff]/15":""}`}>{index===0&&<td rowSpan={part.bars.length} className="border-r border-[#d8df00] p-1 text-center font-bold text-[#f2f500]"><span className="mx-auto block max-w-16 break-words [writing-mode:vertical-rl] rotate-180">{part.name}</span><small className="mt-1 block text-[9px] text-[#00e5ff] [writing-mode:horizontal-tb] rotate-0">SL: {part.qty}</small></td>}<td className="border-r border-[#d8df00] text-center text-[#00e5ff]">{bar.mark}</td><td className="border-r border-[#d8df00] px-1"><DimensionedBar bar={bar}/></td><td className="border-r border-[#d8df00] text-center">{bar.diameter}</td><td className="border-r border-[#d8df00] text-center">{fmt(result.lengthOne*1000,0)}</td><td className="border-r border-[#d8df00] text-center">{fmt(n(bar.qty),0)}</td><td className="border-r border-[#d8df00] text-center">{fmt(result.bars,0)}</td><td className="border-r border-[#d8df00] text-center">{fmt(result.totalLength)}</td><td className="text-center">{fmt(result.weight)}</td></tr>}))}{visibleMembers.every(part=>part.bars.length===0)&&<tr className="border-t border-[#d8df00]"><td colSpan={9} className="p-12 text-center text-[#98a2b3]">Chưa có thanh thép — nhập thông số ở bàn điều khiển phía dưới</td></tr>}</tbody>
     </table>
    </div>
   </div>
  </div>

  <div className="border-y border-[#aebdca] bg-[#f4f6f8] p-2">
   <div className="flex gap-1 overflow-x-auto pb-1">{shapeOrder.map(shape=><button type="button" key={shape} onClick={()=>chooseShape(shape)} title={shapeNames[shape]} className={`min-w-28 shrink-0 rounded border px-2 py-1 ${draft.shape===shape?"border-[#168ac0] bg-[#e8f6fc] text-[#0879ad]":"border-[#b9c5cf] bg-white text-[#52677f]"}`}><ShapeSvg shape={shape} className="mx-auto h-7 w-20"/><span className="block truncate text-[9px] font-bold">{shapeNames[shape]}</span></button>)}</div>
  </div>

  <div className="grid xl:grid-cols-[230px_minmax(0,1fr)_280px]">
   <aside className="border-b border-[#b8c4cf] bg-[#f4f7f9] p-3 xl:border-r xl:border-b-0">
    <div className="flex items-center gap-2"><label className="min-w-0 flex-1 text-[10px] font-extrabold uppercase tracking-wider text-[#667085]">Bảng thống kê<select value={sheet.id} onChange={e=>{const next=sheets.find(item=>item.id===Number(e.target.value));if(next){setSheetId(next.id);setMemberId(next.members[0].id);setShowAll(false)}}} className="mt-1 h-9 w-full rounded border bg-white px-2 text-xs font-bold normal-case tracking-normal text-[#344054]">{sheets.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" onClick={addSheet} className="mt-4 grid size-9 place-items-center rounded border bg-white"><Plus size={15}/></button></div>
    <div className="mt-3 flex items-center justify-between"><p className="text-[10px] font-extrabold uppercase tracking-wider text-[#667085]">Tên cấu kiện</p><button type="button" onClick={()=>addMember()} className="grid size-7 place-items-center rounded bg-[#dce6ee]"><Plus size={14}/></button></div>
    <div className="mt-1 max-h-48 space-y-1 overflow-auto">{sheet.members.map(item=><button type="button" key={item.id} onClick={()=>{setMemberId(item.id);setShowAll(false);resetDraft()}} className={`w-full rounded border px-2 py-2 text-left text-xs ${item.id===member.id&&!showAll?"border-[#7bc8ea] bg-[#e8f6fc] font-bold text-[#0879ad]":"border-[#dce5ef] bg-white"}`}><span className="block truncate">{item.name}</span><small className="text-[#667085]">SL: {item.qty} · {item.bars.length} thanh</small></button>)}</div>
    <div className="mt-2 grid grid-cols-2 gap-1"><button type="button" onClick={()=>addMember(member)} className="flex items-center justify-center gap-1 rounded border bg-white px-2 py-2 text-[10px] font-bold"><Copy size={13}/>Sao chép</button><button type="button" onClick={removeMember} disabled={sheet.members.length===1} className="flex items-center justify-center gap-1 rounded border bg-white px-2 py-2 text-[10px] font-bold text-[#d92d20] disabled:opacity-30"><Trash2 size={13}/>Xóa</button></div>
   </aside>

   <div className="border-b border-[#b8c4cf] bg-white p-3 xl:border-r xl:border-b-0">
    <div className="grid gap-2 sm:grid-cols-[minmax(180px,1fr)_100px]"><label className="text-[10px] font-bold text-[#52677f]">Tên cấu kiện<input value={member.name} onChange={e=>changeMember(current=>({...current,name:e.target.value}))} disabled={showAll} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm font-bold disabled:bg-[#f2f4f7]"/></label><label className="text-[10px] font-bold text-[#52677f]">Số lượng<input type="number" min="1" value={member.qty} onChange={e=>changeMember(current=>({...current,qty:e.target.value}))} disabled={showAll} className="mt-1 h-9 w-full rounded border bg-white px-2 text-right text-sm disabled:bg-[#f2f4f7]"/></label></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-4"><label className="text-[10px] font-bold text-[#52677f]">Số hiệu<input value={draft.mark} onChange={e=>editDraft("mark",e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm"/></label><label className="text-[10px] font-bold text-[#52677f]">Đường kính<select value={draft.diameter} onChange={e=>editDraft("diameter",e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm">{[6,8,10,12,14,16,18,20,22,25,28,32].map(d=><option key={d} value={d}>Ø{d}</option>)}</select></label><label className="text-[10px] font-bold text-[#52677f]">Số thanh<input type="number" min="0" value={draft.qty} onChange={e=>editDraft("qty",e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm"/></label><label className="text-[10px] font-bold text-[#52677f]">Số mối nối<input type="number" min="0" value={draft.laps} onChange={e=>editDraft("laps",e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm"/></label></div>
    <div className="mt-2 grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{shapeFields[draft.shape].map(key=><label key={key} className="text-[10px] font-bold text-[#52677f]">{dimensionLabel(draft.shape,key)}<input type="number" min="0" step={draft.shape==="spiral"&&key==="c"?"1":"1"} value={draft[key]} onChange={e=>editDraft(key,e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm"/></label>)}<label className="text-[10px] font-bold text-[#52677f]">Nối chồng (xD)<input type="number" min="0" value={draft.lapFactor} onChange={e=>editDraft("lapFactor",e.target.value)} className="mt-1 h-9 w-full rounded border bg-white px-2 text-sm"/></label></div>
    <div className="mt-3 flex flex-wrap items-center gap-2 border-t pt-3"><button type="button" onClick={saveBar} className="h-9 rounded bg-[#0b4f88] px-4 text-xs font-bold text-white">{editingId===null?"Thêm":"Cập nhật"}</button><button type="button" onClick={resetDraft} className="h-9 rounded border bg-white px-3 text-xs font-bold">Nhập mới</button><button type="button" onClick={duplicateBar} disabled={editingId===null} className="h-9 rounded border bg-white px-3 text-xs font-bold disabled:opacity-30">Sao chép</button><button type="button" onClick={()=>moveBar(-1)} disabled={editingId===null} className="h-9 rounded border bg-white px-3 text-xs font-bold disabled:opacity-30">Lên</button><button type="button" onClick={()=>moveBar(1)} disabled={editingId===null} className="h-9 rounded border bg-white px-3 text-xs font-bold disabled:opacity-30">Xuống</button><button type="button" onClick={removeBar} disabled={editingId===null} className="h-9 rounded border bg-white px-3 text-xs font-bold text-[#d92d20] disabled:opacity-30">Xóa</button><span className="ml-auto text-xs text-[#52677f]">Dài 1 thanh: <b>{fmt(draftResult.lengthOne)} m</b> · {fmt(draftResult.weight)} kg</span></div>
   </div>

   <aside className="bg-[#f7f9fb] p-3">
    <div className="flex items-center justify-between gap-2"><b className="text-sm text-[#182230]">Tổng hợp cốt thép</b><label className="flex items-center gap-1 text-[10px]"><input type="checkbox" checked={groupByDiameter} onChange={e=>setGroupByDiameter(e.target.checked)}/>Theo Ø</label></div>
    <div className="mt-2 max-h-48 space-y-1 overflow-auto">{summary.map(([label,value])=><div key={label} className="flex justify-between rounded border bg-white px-2.5 py-2 text-xs"><b>{label}</b><span>{fmt(value.length)} m · <b>{fmt(value.weight*(1+n(waste)/100))} kg</b></span></div>)}{summary.length===0&&<p className="rounded border border-dashed p-4 text-center text-xs text-[#98a2b3]">Chưa có số liệu</p>}</div>
    <div className="mt-3 border-t pt-3"><label className="flex items-center justify-between text-xs font-bold text-[#52677f]">Hao hụt <span><input type="number" min="0" step=".5" value={waste} onChange={e=>setWaste(e.target.value)} className="h-8 w-16 rounded border px-2 text-right"/> %</span></label><div className="mt-3 rounded-lg bg-[#0b4f88] p-3 text-white"><small className="block text-[#bde7f8]">Tổng khối lượng</small><strong className="text-xl">{fmt(totalWeight)} kg</strong></div></div>
   </aside>
  </div>
 </section>;
}
function StandardFields({item,footingType,v,set}:{item:ItemId;footingType:FootingType;v:Record<string,string>;set:(k:string,x:string)=>void}){
 const F=(p:{label:string;k:string;unit?:string;step?:string})=><Field {...p} v={v} set={set}/>;
 if(item==="footing"){
  if(footingType==="strip")return <>{F({label:"Tổng chiều dài móng băng",k:"length"})}{F({label:"B — rộng đáy móng",k:"bottomB"})}{F({label:"b — rộng mặt trên",k:"topB"})}{F({label:"H — tổng chiều cao",k:"totalH"})}{F({label:"h — dày bản đế móng BTCT",k:"baseH"})}</>;
  if(footingType==="raft")return <>{F({label:"Chiều dài móng bè",k:"length"})}{F({label:"Chiều rộng móng bè",k:"width"})}{F({label:"Chiều dày bản móng",k:"thickness"})}</>;
  if(footingType==="combined")return <>{F({label:"L — chiều dài bản móng liên hợp",k:"length"})}{F({label:"B — chiều rộng bản móng",k:"width"})}{F({label:"H — chiều dày bản móng",k:"height"})}</>;
  if(footingType==="pile")return <>{F({label:"Chiều dài đài cọc",k:"length"})}{F({label:"Chiều rộng đài cọc",k:"width"})}{F({label:"Chiều cao đài cọc",k:"height"})}{F({label:"Đường kính cọc",k:"pileDiameter"})}{F({label:"Chiều dài mỗi cọc",k:"pileLength"})}{F({label:"Số cọc trong một đài",k:"pileCount",unit:"cọc",step:"1"})}</>;
  if(footingType==="stepped")return <>{F({label:"A — dài bậc dưới",k:"bottomA"})}{F({label:"B — rộng bậc dưới",k:"bottomB"})}{F({label:"Chiều cao bậc dưới",k:"baseH"})}{F({label:"a — dài bậc trên",k:"topA"})}{F({label:"b — rộng bậc trên",k:"topB"})}{F({label:"Chiều cao bậc trên",k:"upperH"})}</>;
  return <>{F({label:"A — chiều dài đáy",k:"bottomA"})}{F({label:"B — chiều rộng đáy",k:"bottomB"})}{F({label:"a — chiều dài mặt trên",k:"topA"})}{F({label:"b — chiều rộng mặt trên",k:"topB"})}{F({label:"H — tổng chiều cao",k:"totalH"})}{F({label:"h — dày bản đế móng BTCT",k:"baseH"})}</>;
 }
 if(item==="stair")return <>{F({label:"Chiều rộng vế thang",k:"stairWidth"})}{F({label:"Chiều cao bậc",k:"rise"})}{F({label:"Chiều rộng mặt bậc",k:"tread"})}{F({label:"Số bậc",k:"steps",unit:"bậc",step:"1"})}{F({label:"Chiều dày bản thang",k:"waist"})}</>;
 if(["blinding","slab","floorBase","floorTile"].includes(item))return <>{F({label:"Chiều dài",k:"length"})}{F({label:"Chiều rộng",k:"width"})}{item!=="floorTile"&&F({label:"Chiều dày",k:"thickness"})}{item==="floorTile"&&<>{F({label:"Cạnh dài viên gạch",k:"tileW"})}{F({label:"Cạnh rộng viên gạch",k:"tileH"})}</>}</>;
 if(["masonry","plaster","wallTile","paint"].includes(item))return <>{F({label:"Tổng chiều dài tường",k:"length"})}{F({label:"Chiều cao tường",k:"height"})}{F({label:"Diện tích cửa cần trừ",k:"openings",unit:"m²"})}{item==="masonry"&&F({label:"Chiều dày tường",k:"thickness"})}{item==="plaster"&&<>{F({label:"Chiều dày lớp trát",k:"thickness"})}{F({label:"Số mặt trát",k:"sides",unit:"mặt",step:"1"})}</>}{item==="wallTile"&&<>{F({label:"Cạnh dài viên gạch",k:"tileW"})}{F({label:"Cạnh rộng viên gạch",k:"tileH"})}</>}{item==="paint"&&<>{F({label:"Số mặt sơn",k:"sides",unit:"mặt",step:"1"})}{F({label:"Độ phủ sơn",k:"coverage",unit:"m²/L"})}{F({label:"Số lớp phủ",k:"coats",unit:"lớp",step:"1"})}</>}</>;
 if(["pedestal","column"].includes(item))return <>{F({label:"Chiều cao cấu kiện",k:"length"})}{F({label:"Cạnh thứ nhất",k:"width"})}{F({label:"Cạnh thứ hai",k:"height"})}</>;
 if(["gradeBeam","beam"].includes(item))return <>{F({label:"Tổng chiều dài",k:"length"})}{F({label:"Bề rộng",k:"width"})}{F({label:"Chiều cao",k:"height"})}</>;
 return <>{F({label:"Chiều dài",k:"length"})}{F({label:"Chiều rộng",k:"width"})}{F({label:"Chiều cao",k:"height"})}</>;
}

export function MaterialCalculator(){
 const [item,setItem]=useState<ItemId>("blinding"),[footingType,setFootingType]=useState<FootingType>("isolated"),[v,setV]=useState(defaults),[grade,setGrade]=useState<keyof typeof mixes>("M100");
 const set=(k:string,x:string)=>setV(s=>({...s,[k]:x}));
 const chooseItem=(id:ItemId)=>{setItem(id);setGrade(current=>id==="blinding"?(current==="M100"||current==="M150"?current:"M100"):(current==="M100"||current==="M150"?"M250":current))};
 const results=useMemo(()=>{const q=n(v.qty),loss=1+n(v.waste)/100;let primary=0;const out:Result[]=[];if(item==="rebar")return {primary:0,out:[{label:"Chế độ",value:"Bóc theo từng thanh"},{label:"Kết quả",value:"Xem bảng thống kê ở cột giữa"}]};
  if(item==="footing"){
   if(footingType==="combined"){const combined=n(v.length)*n(v.width)*n(v.height);primary=combined*q;out.push({label:"Bản móng liên hợp BTCT",value:fmt(primary)+" m³",note:"Không gồm cổ cột"})}
   else if(footingType==="raft"){const raft=n(v.length)*n(v.width)*n(v.thickness);primary=raft*q;out.push({label:"Bản móng bè",value:fmt(primary)+" m³"})}
   else if(footingType==="pile"){const cap=n(v.length)*n(v.width)*n(v.height),piles=Math.PI*Math.pow(n(v.pileDiameter),2)/4*n(v.pileLength)*n(v.pileCount);primary=(cap+piles)*q;out.push({label:"Bê tông đài cọc",value:fmt(cap*q)+" m³"},{label:"Bê tông cọc BTCT",value:fmt(piles*q)+" m³",note:fmt(n(v.pileCount)*q,0)+" cọc"})}
   else if(footingType==="strip"){const L=n(v.length),B=n(v.bottomB),b=n(v.topB),H=n(v.totalH),h=Math.min(n(v.baseH),H),s=Math.max(H-h,0),base=L*B*h,bevel=L*(B+b)/2*s;primary=(base+bevel)*q;out.push({label:"Bản đế móng băng BTCT",value:fmt(base*q)+" m³"},{label:"Phần vát móng băng",value:fmt(bevel*q)+" m³"})}
   else if(footingType==="stepped"){const lower=n(v.bottomA)*n(v.bottomB)*n(v.baseH),upper=n(v.topA)*n(v.topB)*n(v.upperH);primary=(lower+upper)*q;out.push({label:"Bậc móng dưới",value:fmt(lower*q)+" m³"},{label:"Bậc móng trên",value:fmt(upper*q)+" m³"})}
   else {const A=n(v.bottomA),B=n(v.bottomB),a=n(v.topA),b=n(v.topB),H=n(v.totalH),h=Math.min(n(v.baseH),H),s=Math.max(H-h,0),base=A*B*h,bevel=s/6*(2*A*B+2*a*b+A*b+a*B);primary=(base+bevel)*q;out.push({label:"Bản đế móng BTCT",value:fmt(base*q)+" m³"},{label:"Phần vát móng BTCT",value:fmt(bevel*q)+" m³"})}
  }
  else if(item==="stair"){const rise=n(v.rise),tread=n(v.tread),steps=n(v.steps),W=n(v.stairWidth),waist=n(v.waist);const inclined=Math.hypot(rise*steps,tread*steps);const slab=inclined*W*waist,stepsVol=steps*rise*tread*W/2;primary=(slab+stepsVol)*q;out.push({label:"Bản thang nghiêng",value:fmt(slab*q)+" m³"},{label:"Các bậc",value:fmt(stepsVol*q)+" m³"})}
  else if(["pedestal","gradeBeam","column","beam"].includes(item))primary=n(v.length)*n(v.width)*n(v.height)*q;
  else if(["blinding","slab","floorBase"].includes(item))primary=n(v.length)*n(v.width)*n(v.thickness)*q;
  else {const gross=n(v.length)*n(v.height)*q,net=Math.max(gross-n(v.openings),0);
   if(item==="masonry"){const vol=net*n(v.thickness);const mortar=vol*.28*loss;out.push({label:"Diện tích tường",value:fmt(net)+" m²"},{label:"Khối lượng tường",value:fmt(vol)+" m³"},{label:"Gạch tiêu chuẩn",value:Math.ceil(vol*550*loss)+" viên",note:"Gạch 220×105×60 mm"},{label:"Vữa xây",value:fmt(mortar)+" m³"},{label:"Xi măng xây",value:fmt(mortar*300,0)+" kg"},{label:"Cát xây",value:fmt(mortar*1.05)+" m³"});return {primary:vol,out}}
   if(item==="plaster"){const area=net*n(v.sides),mortar=area*n(v.thickness)*loss;out.push({label:"Diện tích trát",value:fmt(area)+" m²"},{label:"Vữa trát",value:fmt(mortar)+" m³"},{label:"Xi măng",value:fmt(mortar*300,0)+" kg"},{label:"Cát mịn",value:fmt(mortar*1.05)+" m³"});return {primary:area,out}}
   if(item==="wallTile"){const area=net*loss,tile=n(v.tileW)*n(v.tileH);out.push({label:"Diện tích mua",value:fmt(area)+" m²"},{label:"Số viên gạch",value:Math.ceil(area/tile)+" viên"},{label:"Keo dán gạch",value:fmt(area*5,0)+" kg"});return {primary:area,out}}
   if(item==="paint"){const area=net*n(v.sides),liters=area*n(v.coats)/n(v.coverage)*loss;out.push({label:"Diện tích sơn",value:fmt(area)+" m²"},{label:"Sơn lót",value:fmt(area/n(v.coverage)*loss)+" lít"},{label:"Sơn phủ",value:fmt(liters)+" lít"},{label:"Bột bả (tham khảo)",value:fmt(area*1.2,0)+" kg"});return {primary:area,out}}
   const area=n(v.length)*n(v.width)*q*loss,tile=n(v.tileW)*n(v.tileH);out.push({label:"Diện tích mua",value:fmt(area)+" m²"},{label:"Số viên gạch",value:Math.ceil(area/tile)+" viên"},{label:"Keo dán gạch",value:fmt(area*5,0)+" kg"});return {primary:area,out}
  }
  const total=primary*loss;if(concreteIds.has(item)){const m=mixes[grade];out.push({label:item==="blinding"?"Bê tông lót có hao hụt":item==="footing"?"Bê tông móng kết cấu có hao hụt":"Bê tông có hao hụt",value:fmt(total)+" m³"},{label:"Xi măng PCB40",value:fmt(total*m.cement,0)+" kg",note:"≈ "+Math.ceil(total*m.cement/50)+" bao 50 kg"},{label:"Cát bê tông",value:fmt(total*m.sand)+" m³"},{label:item==="blinding"?"Đá 4×6":"Đá 1×2",value:fmt(total*m.stone)+" m³"},{label:"Nước trộn",value:fmt(total*m.water,0)+" lít"})}
  if(item==="floorBase"){out.push({label:"Ba ta nền có hao hụt",value:fmt(total)+" m³"},{label:"Xi măng PCB30",value:fmt(total*191,0)+" kg"},{label:"Cát bê tông",value:fmt(total*.548)+" m³"},{label:"Đá 4×6 quy đổi",value:fmt(total*.893)+" m³"},{label:"Nước",value:fmt(total*162,0)+" lít"})}
  return {primary,out};
 },[item,footingType,v,grade]);
 const areaItems=["masonry","plaster","wallTile","paint"].includes(item);
 const activeGroup=groups.find(group=>group.items.some(([id])=>id===item))!;
 const activeFootingName=footingTypes.find(([id])=>id===footingType)?.[1];
 const desktopMenu=<aside className="sticky top-[84px] hidden max-h-[calc(100dvh-96px)] overflow-y-auto rounded-2xl border border-[#dfe7ef] bg-white p-3 shadow-sm lg:block">
  <div className="mb-3 flex items-center gap-2.5 rounded-xl bg-[#073b74] p-3 text-white"><span className="grid size-8 place-items-center rounded-full bg-white/15 font-extrabold">1</span><div><small className="font-bold text-[#bde7f8]">BƯỚC ĐẦU TIÊN</small><h2 className="text-sm font-extrabold">Chọn công tác</h2></div></div>
  {groups.map(group=><div key={group.title} className="mb-4 last:mb-0"><p className="px-2 pb-1.5 text-[11px] font-extrabold uppercase tracking-[.1em] text-[#98a2b3]">{group.title}</p><div className="space-y-1">{group.items.map(([id,label])=><button type="button" key={id} onClick={()=>chooseItem(id)} className={`group flex w-full items-center justify-between rounded-lg px-2.5 py-2 text-left text-[13px] font-semibold ${item===id?"bg-[#e8f6fc] text-[#168ac0]":"text-[#475467] hover:bg-[#f5f7f9]"}`}><span>{label}</span><ChevronRight size={14}/></button>)}</div></div>)}
 </aside>;
 const mobileMenu=<section className="lg:hidden"><div className="mb-2 flex justify-between"><b className="text-xs uppercase tracking-wider text-[#667085]">Chọn hạng mục</b><span className="text-xs font-bold text-[#168ac0]">{activeGroup.title}</span></div><div className="flex max-w-full gap-2 overflow-x-auto pb-2 scrollbar-none">{groups.flatMap(group=>group.items).map(([id,label])=><button type="button" key={id} onClick={()=>chooseItem(id)} className={`shrink-0 rounded-full border px-4 py-2.5 text-sm font-bold ${item===id?"border-[#229ed9] bg-[#229ed9] text-white":"border-[#dfe7ef] bg-white text-[#475467]"}`}>{label}</button>)}</div></section>;
 if(item==="rebar")return <div className="space-y-4">
  <section className="rounded-2xl border border-[#dfe7ef] bg-white px-5 py-4 shadow-sm"><p className="text-xs font-extrabold tracking-[.12em] text-[#168ac0]">TIỆN ÍCH KỸ THUẬT</p><div className="mt-1 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-extrabold tracking-[-.035em] text-[#182230]">Thống kê cốt thép</h1><p className="mt-1 text-sm leading-6 text-[#667085]">Lập bảng, xem trước hình dạng thanh và tổng hợp khối lượng trong một không gian làm việc riêng.</p></div><span className="w-fit rounded-full bg-[#e8f6fc] px-3 py-1.5 text-xs font-bold text-[#0879ad]">Chế độ chuyên dụng</span></div></section>
  {mobileMenu}
  <div className="grid items-start gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
   {desktopMenu}
   <main className="min-w-0"><RebarTakeoff/></main>
  </div>
 </div>;
 const resultPanel=<section className="overflow-hidden rounded-2xl border border-[#c9d9e8] bg-white shadow-[0_8px_30px_rgba(7,59,116,.09)]"><div className="bg-[#0b4f88] p-4 text-white"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/10"><Calculator size={21}/></span><div><p className="text-[10px] font-bold tracking-wider text-[#bde7f8]">BƯỚC 4 · KẾT QUẢ</p><h2 className="text-lg font-extrabold">{item==="rebar"?"Thống kê cốt thép":"Phiếu dự trù vật tư"}</h2></div></div><p className="mt-3 text-sm text-white/75">{item==="footing"?activeFootingName:names[item]}</p></div><div className="p-3"><div className="overflow-hidden rounded-xl border"><div className="divide-y">{results.out.map((row,index)=><div key={row.label} className={`grid grid-cols-[minmax(0,1fr)_auto] gap-3 px-3 py-2.5 ${index===0?"bg-[#eef9fd]":index%2===0?"bg-[#fbfcfd]":"bg-white"}`}><span className="text-sm font-semibold text-[#475467]">{row.label}</span><span className="text-right text-sm"><b className="block">{row.value}</b>{row.note&&<small className="text-[#667085]">{row.note}</small>}</span></div>)}</div></div><p className="mt-2 rounded-lg bg-[#f5f7f9] p-2.5 text-xs leading-5 text-[#667085]">Dự trù sơ bộ; nghiệm thu phải theo hồ sơ thiết kế và quy cách thực tế.</p></div></section>;
 return <div className="grid items-start justify-center gap-5 lg:grid-cols-[220px_minmax(0,700px)] xl:grid-cols-[220px_minmax(0,700px)_320px]">
  {desktopMenu}
  <div className="min-w-0 space-y-4">
   <section className="rounded-2xl border border-[#dfe7ef] bg-white px-5 py-4 shadow-sm"><p className="text-xs font-extrabold tracking-[.12em] text-[#168ac0]">TIỆN ÍCH DỰ TRÙ</p><h1 className="mt-1 text-2xl font-extrabold tracking-[-.035em] text-[#182230]">Tính khối lượng và vật tư xây dựng</h1><p className="mt-1.5 text-sm leading-6 text-[#667085]">Chọn công tác, nhập kích thước thực tế và nhận bảng vật liệu tương ứng.</p></section>
   {mobileMenu}
   <section className="flex flex-col gap-3 rounded-2xl border border-[#dfe7ef] bg-white p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[#e8f6fc] font-extrabold text-[#168ac0]">2</span><div><p className="text-xs font-bold uppercase tracking-wider text-[#168ac0]">{activeGroup.title}</p><h2 className="mt-1 text-xl font-extrabold tracking-[-.025em] text-[#182230]">{names[item]}</h2><p className="mt-0.5 text-xs text-[#667085]">Nhập kích thước thực tế để lập bảng dự trù.</p></div></div><span className="w-fit rounded-full bg-[#f0f4f8] px-3 py-1.5 text-xs font-bold text-[#52677f]">Tự động quy đổi đơn vị</span></section>
   <section className="rounded-2xl border border-[#dfe7ef] bg-white shadow-sm"><div className="border-b px-4 py-3"><div className="flex gap-3"><span className="grid size-8 place-items-center rounded-full bg-[#f0f4f8] font-extrabold text-[#52677f]">3</span><div><h3 className="font-extrabold text-[#182230]">{item==="rebar"?"Bảng thống kê cốt thép":"Thông số đo bóc"}</h3><p className="text-xs text-[#667085]">{item==="rebar"?"Khai báo từng thanh và tổng hợp theo đường kính.":"Điền các kích thước của hạng mục."}</p></div></div></div><div className="p-4">{item==="footing"&&<div className="mb-4 rounded-xl border border-[#dcebf3] bg-[#f5fbfe] p-3"><label><span className="mb-2 block text-sm font-extrabold text-[#182230]">Loại móng</span><select value={footingType} onChange={e=>setFootingType(e.target.value as FootingType)} className="h-10 w-full rounded-lg border bg-white px-3 text-sm font-semibold">{footingTypes.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><FootingPreview type={footingType}/><p className="mt-3 rounded-lg border border-[#b9e2f2] bg-white px-3 py-2 text-xs leading-5 text-[#356078]"><b>Phạm vi tính:</b> chỉ tính đúng hình thể móng đã chọn. Không bao gồm bê tông lót, cổ cột, giằng móng hoặc cấu kiện không thể hiện trên hình.</p></div>}{item!=="rebar"&&<div className="grid gap-x-4 gap-y-3 sm:grid-cols-2"><StandardFields item={item} footingType={footingType} v={v} set={set}/><Field label={areaItems?"Số khu vực":"Số lượng cấu kiện"} k="qty" v={v} set={set} unit="cái" step="1"/><Field label="Hao hụt dự kiến" k="waste" v={v} set={set} unit="%"/></div>}
    {concreteIds.has(item)&&<div className="mt-4 rounded-xl border border-[#dcebf3] bg-[#f5fbfe] p-4"><label><span className="mb-2 block text-sm font-extrabold">Cấp phối bê tông</span><select value={grade} onChange={e=>setGrade(e.target.value as keyof typeof mixes)} className="h-9 w-full rounded-lg border bg-white px-3.5 font-semibold">{item==="blinding"?<><option value="M100">M100 · PCB40 · đá 4×6</option><option value="M150">M150 · PCB40 · đá 4×6</option></>:<><option value="M200">M200 · PCB40 · đá 1×2</option><option value="M250">M250 · PCB40 · đá 1×2</option><option value="M300">M300 · PCB40 · đá 1×2</option></>}</select></label></div>}
    {(item==="masonry"||item==="plaster")&&<p className="mt-4 rounded-xl border border-[#f2dfb6] bg-[#fff9ea] p-4 text-sm leading-6 text-[#7a5612]"><b>Hệ số dự trù:</b> hiệu chỉnh theo loại gạch, mác vữa và cấp phối thực tế.</p>}{item==="rebar"&&<RebarTakeoff/>}</div>
   </section>
   <div className="xl:hidden">{resultPanel}</div>
   <section className="rounded-2xl border bg-white p-4 text-xs leading-6 text-[#52677f]"><b className="text-[#182230]">Lưu ý kỹ thuật:</b> cấp phối bê tông tham khảo Phụ lục VII Thông tư 38/2026/TT-BXD. Hao hụt và định mức có thể thay đổi theo sản phẩm, thiết kế và điều kiện thi công.</section>
  </div>
  <aside className="sticky top-[84px] hidden xl:block">{resultPanel}</aside>
 </div>
}